### ISSUE TITLE
WebpackError: ReferenceError: regeneratorRuntime is not defined - Gatsby build error

### ISSUE THREAD

**Issue by alessandrocalia** [Tintef/react-google-places-autocomplete#100]
I start to have this problem from 2.2.0 in a gatsby project (it works only with a downgrade to 2.1.0). It works fine in develop, but once you try to build you will get this error:

-----------------------------------------------
ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

  428 |     var _componentDidMount = _asyncToGenerator(
  429 |     /*#__PURE__*/
> 430 |     regeneratorRuntime.mark(function _callee() {
      | ^
  431 |       var _this$props3, apiKey, onLoadFailed;
  432 | 
  433 |       return regeneratorRuntime.wrap(function _callee$(_context) {

  WebpackError: ReferenceError: regeneratorRuntime is not defined

  - react-google-places-autocomplete.esm.js:430
    node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.esm.js:430:1

  - react-google-places-autocomplete.esm.js:472
    node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.esm.js:472:4

  - react-google-places-autocomplete.esm.js:530
    node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.esm.js:530:3

**Comment by Tintef** [comment]
@alessandrocalia  Can any of you guys test the 2.3.0-beta.1 version?

```yarn add react-google-places-autocomplete@2.3.0-beta.1```

It's working for me in a next project and I do think it's the same issue, but I would like someone else to give it a try. Thanks!

**Comment by Tintef** [comment]
Fix released on v2.3.0

If it doesn't work, please comment here or open a new issue

**Comment by alessandrocalia** [comment]
Yes, I used 2.3.0 and it works. Thank you!
