### ISSUE TITLE
Set active suggestion on mouse hover

### ISSUE THREAD

**Issue by orenk86** [Tintef/react-google-places-autocomplete#102]
Hi,
First of all, loving the library! Awesome job! 👍 
I want to set the currently active suggestion in response to a mouse hover.

I managed to do this with CSS using `:hover` but the suggestion that is already active from scrolling with my keyboard arrows remains active (in addition to what I'm hovering over).

Any easy way to do this? Thanks!

**Comment by Tintef** [comment]
Hi @orenk86, thanks for the kind words 🤗 Glad to hear you are enjoying the library!

The component calls [this method](https://github.com/Tintef/react-google-places-autocomplete/blob/master/src/GooglePlacesAutocomplete/index.js#L137-L156) whenever a keydown event occurs, and that set an internal `activeSuggestion` state property.

So, my guess is that we are missing a `onHover` method to set that internal `activeSuggestion` state property 🤔 

It should be a really easy fix, how do you feel about giving it a try?

I can update the readme with the usual steps I take to test whatever I change I'm working on (might not be the best tho 😅 , but it works for me!)

**Comment by orenk86** [comment]
Sure @Tintef , after a quick look at the code, it seems pretty easy to add. I'll give it a go during the weekend 🙂

As for the Readme, yes please update it if you have time. Thanks!

**Comment by Tintef** [comment]
Awesome! I added that [here](https://github.com/Tintef/react-google-places-autocomplete#how-to-contribute)

Thanks!

**Comment by orenk86** [comment]
Here you go: https://github.com/Tintef/react-google-places-autocomplete/pull/104

**Comment by Tintef** [comment]
@orenk86 Awesome, I'll take a look as soon as I can.

Was the how to contribute guide useful?

**Comment by orenk86** [comment]
Yes it was. I didn't know about `yalc` before. Testing local packages suddenly became much easier :)

**Comment by Tintef** [comment]
@orenk86 Merged and published on v2.3.2, thanks!

**Comment by yh10106699** [comment]
Hi, I am using v2.3.2. This feature does not work. Is that because I overwrite the onChange and onKeydown in the renderInput props? Do we have props.onMouseEnter(event) like props.onChange(event) and props.onKeyDown(event) ? The arrow key functions works fine for me on changing the active suggestions.

**Comment by yh10106699** [comment]
I found it's because the onHoverOverSuggestions is not returned in renderSuggestions. In renderinput, onChange and onKeyDown are returned. Is there any chance to change this?
