### ISSUE TITLE
autocompletionRequest not recognized

### ISSUE THREAD

**Issue by cemeai** [Tintef/react-google-places-autocomplete#103]
version: 2.3.0
`let LatLng = {lat: 0, lng: 0}`
`<GooglePlacesAutocomplete`
 `     apiKey='xxxx'`
`      onSelect={console.log}`
 `       withSessionToken={true}`
`        debounce={300}`
`        autocompletionRequest={`
`          location: LatLng`
 `       }`
`      />`

I am getting this error

> Overload 1 of 2, '(props: Readonly<GooglePlacesAutocompleteProps>): GooglePlacesAutocomplete', gave the following error.
>     Type 'Location<PoorMansUnknown>' has no properties in common with type 'autocompletionRequestType'.
>   Overload 2 of 2, '(props: GooglePlacesAutocompleteProps, context?: any): GooglePlacesAutocomplete', gave the following error.
>     Type 'Location<PoorMansUnknown>' has no properties in common with type 'autocompletionRequestType'.ts(2769)

**Comment by Tintef** [comment]
@cemeai You are not passing an object. Try this:

```
let LatLng = {lat: 0, lng: 0}
<GooglePlacesAutocomplete
	apiKey='xxxx'
	onSelect={console.log}
	withSessionToken={true}
	debounce={300}
	autocompletionRequest={{
		location: LatLng
	}}
/>
```

**Comment by cemeai** [comment]
thanks thats is my bad, forgot first {} are not actually the object. sorry for the silly mistake
