### ISSUE TITLE
Getting the distance

### ISSUE THREAD

**Issue by cemeai** [Tintef/react-google-places-autocomplete#105]
According to google ocumentation you need to send the origin param to get the distance in meters. Is this being managed cause I dont seem to be getting the distance in the result.

I know this module doesnt manage origin just location as to sent the lat long, is there a work around or a fix I can use?

**Comment by Tintef** [comment]
@cemeai Can you point the documentation you are referring to?

**Comment by cemeai** [comment]
Sure here it is the section i am tlking about
> origin — The origin point from which to calculate straight-line distance to the destination (returned as distance_meters). If this value is omitted, straight-line distance will not be returned. Must be specified as latitude,longitude.

and the link https://developers.google.com/places/web-service/autocomplete

**Comment by Tintef** [comment]
@cemeai By a quick read of those docs my guess is that it should be added on the [autocompletionRequest](https://github.com/Tintef/react-google-places-autocomplete#autocompletionrequest). But I don't think that would work.

What this library uses is actually the [places library](https://developers.google.com/maps/documentation/javascript/places), and I can't seem to find a parameter or configuration to indicate distance in there 🤔

**Comment by redimongo** [comment]
@cemeai & @Tintef  you are right you can't do it that way. However a solution to your problem would be to pass the selected location to 

```
import { geocodeByAddress } from 'react-google-places-autocomplete';
 
// `results` is an entire payload from Google API.
geocodeByAddress('Mohali, Punjab')
  .then(results => console.log(results))
  .catch(error => console.error(error));
```

Now how would you do this:
(NOTE: NOT TESTED)
 ```
  <GooglePlacesAutocomplete
                     autocompletionRequest={{
                        componentRestrictions: {
                          country: ['au', 'nz'],
                        }
                      }}
                    onSelect={({description}) => {
                        console.log(description);
                       geocodeByAddress(description)
  .then(results => console.log(results))
  .catch(error => console.error(error));
                      }}
                   
                    />

**Comment by Tintef** [comment]
I'll close this one as we confirmed it's not doable with google places API
