### ISSUE TITLE
Mulitple locations

### ISSUE THREAD

**Issue by redimongo** [Tintef/react-google-places-autocomplete#106]
I am trying to create away for a person to do multiple locations. For example say I have 
```
<GooglePlacesAutocomplete
                     autocompletionRequest={{
                        componentRestrictions: {
                          country: ['au', 'nz'],
                        }
                      }}
                    onSelect={({description}) => {
                        console.log(description);
                        setFieldValue(
                          "targetLocation",
                          description !== null ? description : initialValues.targetLocation
                        );
                      }}
                   
                    />
```
That allows me to only select 1 location. But I want to allow users to have up to 5 different locations.
Is their anyway we can put this inside https://material-ui.com/components/autocomplete/

Thank/s

**Comment by Tintef** [comment]
@redimongo So you would like a multi-select type feature? If so, that's not supported.

I'm indeed planning a possible rewrite to use react-select under the hood, that should give that ability, but I don't have any idea on when that may happen.

A possible solution for you is to add the selections to a list underneath the select box or something like that. So the select is still a "single value select", but you can control and show the selected locations.

**Comment by redimongo** [comment]
@Tintef So I have a work around but can't seem to get it to work 100% Basically what happening is, its only updating the last array.

https://codesandbox.io/s/youthful-hofstadter-dp4mx?file=/src/App.js

I know this may not be a direct issue with your script, and I will look at figuring out if I can help improve your code and share it back with you.

But If you have any suggestion with the code above that would be very helpful.

**Comment by redimongo** [comment]
> @redimongo So you would like a multi-select type feature? If so, that's not supported.
> 
> I'm indeed planning a possible rewrite to use react-select under the hood, that should give that ability, but I don't have any idea on when that may happen.
> 
> A possible solution for you is to add the selections to a list underneath the select box or something like that. So the select is still a "single value select", but you can control and show the selected locations.

Is this the file I would need to edit? As I see the input field which if am correct this could be a formik <Field/>
/src/GooglePlacesAutocomplete/index.js

**Comment by Tintef** [comment]
@redimongo Yes, that's the file.

Anyway, I won't accept any PR adding an external library such as formik.

Also, after thinking a bit more you can do something like this: https://codesandbox.io/s/sharp-tharp-s69i1

I think you can also use a custom `renderInput` function to show a multiselect input, doing something like this: https://codesandbox.io/s/agitated-bush-l7s7m

I'll close this issue as this two examples should get you started with doing the multiselect you want.

Feel free to ask if you need anything else!
