### ISSUE TITLE
types how? documentation not clear

### ISSUE THREAD

**Issue by redimongo** [Tintef/react-google-places-autocomplete#107]
So I am trying to get (cities) and I cant work out how I intergrate that into your script.
`
Personally I thought it would be 
```
 <GooglePlacesAutocomplete
                     autocompletionRequest={{
                        types:['administrative_area_level_3'],
                        componentRestrictions: {
                          country: ['au'],
                         
                        }
                      }}
                    onSelect={({description}) => {
                        console.log(description);
                      
                        setFieldValue(
                          "targetLocation",
                          description !== null ? description : initialValues.targetLocation
                       );
                      }}
                   
                    />

```

**Comment by Tintef** [comment]
@redimongo Yes, that's how it should work. You can find the available types [here](https://developers.google.com/places/supported_types#table3).

I think you should use `[(cities)]` for what you want, as "The (cities) type collection instructs the Places service to return results that match locality or administrative_area_level_3." (from the docs linked above).

Also, from my understanding, you can't use `administrative_area_level_3`.

**Comment by redimongo** [comment]
> @redimongo Yes, that's how it should work. You can find the available types [here](https://developers.google.com/places/supported_types#table3).
> 
> I think you should use `['(cities)']` for what you want, as "The (cities) type collection instructs the Places service to return results that match locality or administrative_area_level_3." (from the docs linked above).
> 
> Also, from my understanding, you can't use `administrative_area_level_3`.

That worked, we can close this.
