### ISSUE TITLE
Cant seem to get location from results

### ISSUE THREAD

**Issue by redimongo** [Tintef/react-google-places-autocomplete#108]
So The issue I am running into is the how do I send the results to ```

  geocodeByAddress(description)
                        .then(results => console.log(results))

Like it works, but then I need to send that result to `getLatLng` function and it seems to not work. Based on your plugin code I should be able to do this. in theory I should do something like.
```

<GooglePlacesAutocomplete
                     autocompletionRequest={{
                          types: ["(cities)"],
                        componentRestrictions: {
                          country: ['au'],
                         
                        }
                      }}
                    onSelect={({description}) => {
                        console.log(description);
                        geocodeByAddress(description)
                        .then(results => getLatLng(results))
                       .then(results => console.log(results))
                        .catch(error => console.error(error));
                        setFieldValue(
                          "targetLocation",
                          description !== null ? description : initialValues.targetLocation
                       );
                      }}
                   
                    />
```

This however does not work. Any support here would be great.

**Comment by Tintef** [comment]
@redimongo 

`getLatLng` expects an object, not an array of objects as you're passing.

You can take a look at the [docs here](https://github.com/Tintef/react-google-places-autocomplete#getlatlng-api).
