### ISSUE TITLE
TypeError: Cannot read property 'maps' of undefined

### ISSUE THREAD

**Issue by Magum23** [Tintef/react-google-places-autocomplete#115]
Hello I think, there might be problem with the geocoder utility function since it throws error with an example code which is provided on the website.

![image](https://user-images.githubusercontent.com/49533200/92082335-abce0500-edc4-11ea-8776-084b42c70f01.png)

**Comment by Tintef** [comment]
@Magum23 In order to use the utility function you need to inject Google Maps API, are you injecting it?

You can add this to your `head`:

```
<script
  type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=YOUR_GOOGLE_API_KEY&libraries=places"
/>
```

**Comment by rimpu** [comment]
I have a doubt here @Tintef if we are already using import statement import GooglePlacesAutocomplete, {
  geocodeByPlaceId
} from "react-google-places-autocomplete";

do we still need to write this script to run the geoCode methods ?
