### ISSUE TITLE
Add style to MenuList

### ISSUE THREAD

**Issue by maximiliano-gt** [Tintef/react-google-places-autocomplete#120]
Hello i need to add a style to the MenuList (Dropdown) , how can i do that? there is nothing about styling in the documentation.

Thank you.

**Comment by Tintef** [comment]
@maximiliano-gt You can take a look at customization [here](https://tintef.github.io/react-google-places-autocomplete/docs/examples#customization).

Basically, you need to add [styles to the underlying react-select](https://react-select.com/styles).
