### ISSUE TITLE
Broken textbox.

### ISSUE THREAD

**Issue by codepurse** [Tintef/react-google-places-autocomplete#122]
I have my data in the localstorage and i tried to put in as a defaultInputValue. But the output is like this. 

![2020-09-16 00 16 43 localhost 212eb49cc1ab](https://user-images.githubusercontent.com/47669262/93237095-37c33200-f7b2-11ea-8efa-3bb3b239e935.jpg)

It happens only when the defailtInputValue is the localstorage data.

**Comment by Tintef** [comment]
@codepurse This works for me:
```import React from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";
import "./styles.css";

export default function App() {
  return (
    <div className="App">
      <GooglePlacesAutocomplete
        selectProps={{
          defaultInputValue: localStorage.getItem("value")
        }}
      />
    </div>
  );
}
```

So it doesn't looks like a problem with the library

**Comment by codepurse** [comment]
I dont know but everytime I read the local storage its gets "Local storage not defined" thats why i add the below code.

```
  if (process.browser) {
    global.config.place.deliver.pickoff = localStorage.getItem("pickoff");
  }
```

And I tried the put the global.config in DefaultInputValue and its the same its like broken text.

 ```
<GooglePlacesAutocomplete
          selectProps={{
            defaultInputValue: global.config.place.deliver.pickoff,
            value: address,
            onChange: handleChange,
          }}
          autocompletionRequest={{
            componentRestrictions: {
              country: ["ph"],
            },
          }}
        />
```

**Comment by Tintef** [comment]
@codepurse That looks like it's not related to this library. Try asking on stackoverflow.
