### ISSUE TITLE
Bug, cannot type again after making selection.

### ISSUE THREAD

**Issue by TylerEikenberg** [Tintef/react-google-places-autocomplete#128]
<img width="430" alt="Screen Shot 2020-11-10 at 3 55 00 PM" src="https://user-images.githubusercontent.com/55251251/98732408-196e5280-236d-11eb-8421-2790d05cd608.png">

After typing in the input and making a selection, I can no longer type again in the input to search for something else. Here's my code. 

```
  const [location, setLocation] = useState(null);
  const [coordinates, setCoordinates] = useState({ lat: null, lng: null });

  const handleLocationSelect = async value => {
    setLocation(value);
    const results = await geocodeByAddress(value.label);
    const latLng = await getLatLng(results[0]);
    setCoordinates(latLng);
  };

...
            <GooglePlacesAutocomplete
              debounce={500}
              onLoadFailed={error =>
                console.error('Could not inject Google script', error)
              }
              selectProps={{
                location,
                onChange: handleLocationSelect,
              }}
            />

**Comment by Tintef** [comment]
@TylerEikenberg Are you including your api key? I tried it on [this codesandbox](https://codesandbox.io/s/upbeat-shape-cjzd6) and it's working fine.

If it's still being an issue for you, please create a codesandbox/repo so I can take a look.

**Comment by TylerEikenberg** [comment]
@Tintef Yes, I'm including the api key, I just omitted it from my example. I'm seeming to have the same problem with that code sandbox. Here's a gif I recorded. After selecting **Maryland, USA** my cursor is stuck and I can't delete the selection to search again.
![gpabug](https://user-images.githubusercontent.com/55251251/98822121-68b09380-23fe-11eb-8e8d-9abaec6217fa.gif)

Thanks for the quick reply.

**Comment by anthowm** [comment]
@TylerEikenberg I think is an enhacement, but can be easy handling with onMenuOpen
https://codesandbox.io/s/purple-snow-11eon?file=/src/App.js
Hope it helps

**Comment by TylerEikenberg** [comment]
> @TylerEikenberg I think is an enhacement, but can be easy handling with onMenuOpen
> https://codesandbox.io/s/purple-snow-11eon?file=/src/App.js
> Hope it helps

Thank you, this solves my problem. Although its still strange that I have to clear the whole selection rather than being able to backspace it. But this gets the job done. 👍
