### ISSUE TITLE
Clear Value feature missing/removed?

### ISSUE THREAD

**Issue by XGhozt** [Tintef/react-google-places-autocomplete#129]
What happened to this? I see merge requests and issues about it but they're all out of date. Is this feature still present? I can't seem to get it to work with `useRef()`.

**Comment by Tintef** [comment]
Yes, this feature is still present. Please upgrade to the latest version and use `clearValue` prop from [react select](https://react-select.com/props) as indicated [here](https://tintef.github.io/react-google-places-autocomplete/docs/props#selectprops).

**Comment by e-hop** [comment]
Not working for me using
```
     selectProps={{
                                                value,
                                                isClearable: true,
                                                onChange: setValue,
                                                placeholder:
                                                    "Escribe tu código postal, ciudad o dirección"
                                            }}
```

**Comment by Tintef** [comment]
@e-hop Can you please provide a codesandbox/repo where I can reproduce this?
