### ISSUE TITLE
Cannot read property 'place_id' of undefined

### ISSUE THREAD

**Issue by Goldtek** [Tintef/react-google-places-autocomplete#130]
<AsyncSelect
  62 |       {...selectProps}
  63 |       loadOptions={fetchSuggestions}
> 64 |       getOptionValue={({ value }) => value.place_id}
  65 |     />
  66 |   );
  67 | };

**Comment by Tintef** [comment]
@Goldtek Need more information

**Comment by Goldtek** [comment]
on typing in the address of the location it  throws this error specific there is no value.place_id as you specified in your package

**Comment by usamamashkoor** [comment]
I try to set the value manually like this
`setValue({label:'my address'});`

Then when I try to search from input then I see this error.

Can you please let us know how we can set the custom address? I am getting the custom address from the browser `geolocation.getCurrentPosition`

**Comment by Tintef** [comment]
@Goldtek That's probably an issue with google maps API key for some directions (I can't find which issue, but someone brought this up). If you can provide a way to consistently reproduce this, I'll take a look.

@usamamashkoor Please refer [to this issue](https://github.com/Tintef/react-google-places-autocomplete/issues/126)

**Comment by Tintef** [comment]
Closing this, if someone found a way to consistently reproduce I'll open it again.

**Comment by atawfique21** [comment]
I wanted to post my findings on this. I am using a Controller Component and passing selectProps like this: 

```JS
const [address, setAddress] = useState('');

const setValue = value => {
  ...
  setAddress({ label: value.label }); // <-- This is the issue. 
};

<GooglePlacesAutocomplete
  selectProps={{
    value: address,
    onChange: setValue,
    ...
  }}
/>
```

Instead of setting the state variable to the label, pass the entire value like this and the error will no longer happen: 
```JS
const setValue = value => {
  ...
  setAddress(value); // <-- This is the issue. 
};
```

Hope this helps!
