### ISSUE TITLE
Do I need to google script inside the react or will this package will automatically includes the google maps script?

### ISSUE THREAD

**Issue by usamamashkoor** [Tintef/react-google-places-autocomplete#135]
Hi in the npm package, I can see this example.

```
import React from 'react';
import GooglePlacesAutocomplete from 'react-google-places-autocomplete';

const Component = () => (
  <div>
    <GooglePlacesAutocomplete
      apiKey="****"
    />
  </div>
);

export default Component;
```

My question is this do I need to add the Script tag of google maps inside the react component or not, If I do then can someone let me know where should I include it.

I am talking about this script tag
```
 <Script
   url={`https://maps.googleapis.com/maps/api/js?key=${google_maps_key}&libraries=places`}
  /> 
```

**Comment by Tintef** [comment]
@usamamashkoor If you pass down the `apiKey` prop with your google maps key, you don't need to add a script tag, the package will inject it in your HTML for you.

**Comment by usamamashkoor** [comment]
@Tintef Thanks man, I really appreciate your help bro.
