### ISSUE TITLE
How can I pass a a initial or default value when the page loads

### ISSUE THREAD

**Issue by usamamashkoor** [Tintef/react-google-places-autocomplete#136]
Hi, I want to set an initial google address when the page loads, can someone let me know how we can do that.

Here is what I have tried.

I have an address a Google address as a String which is this
"Faisalabad, Pakistan"
I want to show this address as an initial value when the page loads
Here is my code.

```
const [objQueryData, setObjQueryData] = useState({});
useEffect(() => {
    setObjQueryData({ label: address,value:{description:address}  })
}, []);

<GooglePlacesAutocomplete
    apiKey={KEY}
    selectProps={{
    placeholder: 'Enter full address',
    value: query,
    onChange: handleOnChangeLocation,
    }}
/>
```

But the data is still not showing correctly..?

Can someone let me know how to show the initial values correctly when the page loads?

**Comment by Tintef** [comment]
@usamamashkoor It doesn't look like `query` is defined on your snippet. You should be using `objQueryData`. If you use that one, does it work?

If not, take a look at [this issue](https://github.com/Tintef/react-google-places-autocomplete/issues/126)

**Comment by Tintef** [comment]
Closing as the related issue should work

**Comment by usamamashkoor** [comment]
Thanks @Tintef I have found a solution sorry for the late reply I forgot to change the query in the snippet.
