### ISSUE TITLE
Isn't it a security breach to make API calls with an exposed key from the client side as this component does?

### ISSUE THREAD

**Issue by nicopoore** [Tintef/react-google-places-autocomplete#137]
From what I understand (correct me if I'm wrong), this component would be making API calls with your Google Places API key from the client side, which are visible both from the code (if the API key is passed from a next.config.js file) and from the browser Network tab (regardless of where the API key comes from) to the client, leaving it vulnerable.

Am I missing something on the usage of this component? I couldn't find anything in the docs. I hope I'm wrong cause other than this, the component itself is a godsend!

**Comment by Tintef** [comment]
@nicopoore Veo que sos de Bs. As., así que lo explico en español así se me hace más fácil 😅 

Lo que decís es correcto, la API key queda expuesta, pero esto es inevitable (a no ser que quieras delegar esto a un backend -- lo cual implicaría dos API calls, una a tu backend y tu backend a la API de Google --).

Por suerte, se pueden configurar los dominios que pueden utilizar una API key -- algo así como funciona CORS --, limitando así quienes pueden utilizar tu API key. Esto se hace desde la consola de Google, pero no recuerdo exactamente dónde.

Esto responde tus dudas?

Saludos!

**Comment by nicopoore** [comment]
Claro, me pareció raro porque siempre lo ví delegado al back-end para APIs con rate limits o pagas. Entonces lo que harías es restringir por HTTP y sólo permitir que se hagan calls desde esa misma página web? O por IP, o de otra forma?

**Comment by Tintef** [comment]
@nicopoore Sí, tenes que ir a la consola de google y agregar tu sitio entre los permitidos para utilizar tu API key.
