### ISSUE TITLE
how to get lant lang values by useing place_id or else directly how we get lant lang values

### ISSUE THREAD

**Issue by Agspro12** [Tintef/react-google-places-autocomplete#138]

**Comment by Tintef** [comment]
Use one of the utility fuctions. To fetch by place_id, use [this](https://tintef.github.io/react-google-places-autocomplete/docs/geocode-by-place-id)

**Comment by Gopisuresh-Akula** [comment]
can you please show an example of how to use in component

**Comment by Gopisuresh-Akula** [comment]
moreover, I need   lant lang values of the select place where I'm getting only  place id and reference id

**Comment by Tintef** [comment]
@Gopisuresh-Akula What have you tried?
Step 1. Get the place ID using the autocomplete component.
Step 2. Use the `getLatLng` utility function to get the desired lat/long
