### ISSUE TITLE
Update peer dep

### ISSUE THREAD

**Issue by Edsonzhu** [Tintef/react-google-places-autocomplete#139]
Hi, is it possible to update the peer dep of this project to react 17?

```npm ERR! peer dep missing: react@^16.8.0, required by react-google-places-autocomplete@3.0.0```

**Comment by Tintef** [comment]
@Edsonzhu I tried installing the library on a brand new react project (using 17.0.1) and I was able to install the library (I did get a warning though).

Updating the peer dependency to react 17 is doable (actually supporting 16.8.0 and 17), but it will need some manual testing so I won't be able to create that update until next week probably.

Given this, I would like to help you install the library in the meantime anyway, so can you share a repo or your project configuration so I can replicate the issue?

**Comment by Edsonzhu** [comment]
Hey @Tintef, I think my question was missing information. I could successfully installed and am using it in my project. What I was asking was just to update the peer dependency to remove the warning on the project.

I appreciate your help.

**Comment by Tintef** [comment]
@Edsonzhu Published in 3.1.0 :)
