### ISSUE TITLE
is it possible to do reverse geocoding using this package ?

### ISSUE THREAD

**Issue by aditbharadwaj** [Tintef/react-google-places-autocomplete#140]
i was wondering if its possible to find address using lat and lng using this package ?

**Comment by Tintef** [comment]
@aditbharadwaj It's not currently supported, but it looks like it's doable using [google maps geocoder](https://developers.google.com/maps/documentation/javascript/geocoding#ReverseGeocoding).

I think it would be a great addition, a PR is welcome!

**Comment by Tintef** [comment]
Closed on by #143. Feature added on 3.1.0
