### ISSUE TITLE
how to find out postal code by using  "react-google-places-autocomplete": "1.6.2

### ISSUE THREAD

**Issue by Gopisuresh-Akula** [Tintef/react-google-places-autocomplete#153]
Hi Tintef

Here using  "react-google-places-autocomplete": "1.6.2", 
sometimes I'm facing issue called infinite script loading may l know reasons for that and one more thing can please brief the how to get postal code in  "react-google-places-autocomplete": "1.6.2", 
please  find below attachments for 

![infinte loop]
(https://user-images.githubusercontent.com/42737147/109041780-6811e380-76f5-11eb-9d6b-8d927b90eb00.PNG)
!postal code (https://user-images.githubusercontent.com/42737147/109041821-75c76900-76f5-11eb-9a85-3009bdfe75b9.PNG)

**Comment by Tintef** [comment]
@Gopisuresh-Akula I highly recommend upgrading to 3.x

Not an infinite loop, the library cannot find the google places script. Verify you have it on your document.

For the other one, please send a code snippet or a repo to reproduce.

**Comment by Gopisuresh-Akula** [comment]
"react-google-places-autocomplete": "1.6.2", fit for my requirement I can easily  customize it that's  why I choose  "1.6.2" 
second thing can you share code snippet for postal code in "react-google-places-autocomplete": "1.6.2",

**Comment by Tintef** [comment]
The 3.x version are easily customizable using react-select. And no, I won't share how to do it, you should try doing it yourself and share what you come up with and then I can help you fix it if there's something wrong.

**Comment by Gopisuresh-Akula** [comment]
yeah @Tintef  i upgrade version but customizable using react-select. we can do  using inline style only  if possible can you share classnames to override styles

**Comment by Tintef** [comment]
Check [react-select](https://react-select.com/styles) docs.

**Comment by Gopisuresh-Akula** [comment]
Hey @Tintef  i did this please check  moreover in react-select docs I didn't get how to override classnames if possible   can share code snippet for that  


const customStyles = {
  // option: (provided, state) => ({
  //   ...provided,
  //   borderBottom: '1px dotted pink',
  //   color: state.isSelected ? 'red' : 'blue',
  //   padding: 20,
  // }),
  // control: () => ({
  //   // none of react-select's styles are passed to <Control />
  //   width: 200,
  // }),
  // menu: (provided, state) => ({
  //   ...provided,
  //   width: "25vw",
  //   borderBottom: '1px dotted pink',
  //   color: state.selectProps.menuColor,
  //   padding: 20,
  // }),
  // singleValue: (provided, state) => {
  //   const opacity = state.isDisabled ? 0.5 : 1;
  //   const transition = 'opacity 300ms';

  //   return { ...provided, opacity, transition };
  // }


`
<GooglePlacesAutocomplete
    placeholder={props.placeholder ? props.placeholder : "Where are you going?"}

    
           selectProps={{
            value: location,
            placeholder:"Where are you going?",
            defaultInputValue:defaultplacevalue,
            onChange: handleLocationSelect,
            onFocus: () => {
              console.log("focus");
              setLocation(null);
            },
            styles: {
              ...customStyles
            },

            
          
            isClearable: true
          }}
 
```
