### ISSUE TITLE
ApiNotActivatedMapError on simple component

### ISSUE THREAD

**Issue by golf-n-code** [Tintef/react-google-places-autocomplete#154]
I am using the basic example with **** replaced with my current API Key that is verified as enabled for Javascript Map API. For some reason I am still getting rejected? Am I using the component incorreclty?

![image](https://user-images.githubusercontent.com/68881829/109218968-15800800-7785-11eb-9a17-410c3148b09e.png)

Code:
```
import React from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";

const GoogleAutoComplete: React.FC = () => (
  <div>
    <GooglePlacesAutocomplete apiKey="****" />
  </div>
);

export default GoogleAutoComplete;
```

Referenced Here:
```
import React, { useState, useEffect } from "react";
import GoogleAutoComplete from "../components/AutoComplete";
const Test: React.FC = () => {
  return (
          <div>
            <GoogleAutoComplete />
          </div>
        );
}
```

**Comment by Tintef** [comment]
@golf-n-code Does your key work for the places API?

**Comment by golf-n-code** [comment]
> @golf-n-code Does your key work for the places API?

This was the solution - I thought I only needed JS Maps API. Added Places API and it works. Thank you!
