### ISSUE TITLE
process not defined

### ISSUE THREAD

**Issue by miko1991** [Tintef/react-google-places-autocomplete#157]
Hello,
I am using both Mac and Windows - for dev, and Linux - to deploy, and everything works on Mac and Linux, but on Windows I'm getting error - process not defined. I'm using Webpack and Babel

**Comment by Tintef** [comment]
@miko1991 Please share both the log you're getting and a repository to reproduce your issue.

**Comment by jeremylynch** [comment]
I am experiencing the same but on Mac with gatsby
<img width="988" alt="screen" src="https://user-images.githubusercontent.com/3665457/109890224-a483a780-7cd2-11eb-92c1-d91def938dc8.png">

**Comment by miko1991** [comment]
I solved it by installing "process" and adding it to plugins like so:

edit webpack.config.js

```
module.exports = {
  ...
  plugins: [
      new webpack.ProvidePlugin({
             process: 'process/browser',
      }),
  ],
}
```

**Comment by Tintef** [comment]
@miko1991 @jeremylynch I was able to reproduce this and it's fixed (as far as I was able to test) on version 3.2.2
