### ISSUE TITLE
react-select customization in react-google-places-autocomplete

### ISSUE THREAD

**Issue by Gopisuresh-Akula** [Tintef/react-google-places-autocomplete#158]

**Comment by Gopisuresh-Akula** [comment]
Hey @Tintef i did this please check moreover in react-select docs I didn't get how to override classnames if possible can share code snippet for that

const customStyles = {
// option: (provided, state) => ({
// ...provided,
// borderBottom: '1px dotted pink',
// color: state.isSelected ? 'red' : 'blue',
// padding: 20,
// }),
// control: () => ({
// // none of react-select's styles are passed to
// width: 200,
// }),
// menu: (provided, state) => ({
// ...provided,
// width: "25vw",
// borderBottom: '1px dotted pink',
// color: state.selectProps.menuColor,
// padding: 20,
// }),
// singleValue: (provided, state) => {
// const opacity = state.isDisabled ? 0.5 : 1;
// const transition = 'opacity 300ms';

// return { ...provided, opacity, transition };
// }

`
<GooglePlacesAutocomplete
placeholder={props.placeholder ? props.placeholder : "Where are you going?"}

       selectProps={{
        value: location,
        placeholder:"Where are you going?",
        defaultInputValue:defaultplacevalue,
        onChange: handleLocationSelect,
        onFocus: () => {
          console.log("focus");
          setLocation(null);
        },
        styles: {
          ...customStyles
        },

        
      
        isClearable: true
      }}

**Comment by Tintef** [comment]
You can't override classnames, you need to provide an object as react select docs says.

There's an example on [this library documentation](https://tintef.github.io/react-google-places-autocomplete/docs/examples#customization).
