### ISSUE TITLE
Not working with react-google-map component

### ISSUE THREAD

**Issue by toptalentdev81** [Tintef/react-google-places-autocomplete#159]
I'm using this component with react-google-map component in one page.
And this component is not working.
the reason is importing google map scripts from two components.

Below are console error.
"You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors."

Is there any way to fix this?

**Comment by Tintef** [comment]
Please show the code of your component so I can give you an accurate answer.

But if that's the case, you should only load the script once, so either load the script using this component or react-google-map.

**Comment by Tintef** [comment]
You should, but I just notice that it got removed from react-google-places-autocomplete@3.2.2 by an accident.

Just uploaded react-google-places-autocomplete@3.2.3, please use that version :)

**Comment by toptalentdev81** [comment]
Thanks for your kind and fast reply.

Yeah, without `apiKey` props, this component doesn't load script.
but instead inserting script manually doesn't work.
I added below in the <head> like your document.

```
<script
  type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=MY_GOOGLE_API_KEY&libraries=places"
/>
```

but your components didn't work.
I found that you embedded callback function name when using `apiKey` props.
so I also copied that in above script. but it still didn't work.
can you please check again this?

so below are loaded by `react-google-maps`.

```
<script async="" src="https://maps.googleapis.com/maps/api/js?key=MY_GOOGLE_API_KEY&v=3.exp&libraries=geometry,drawing,places"></script>
```

I want your component work with this script when I omit `apiKey` props.
Please help me.

**Comment by Tintef** [comment]
@toptalentdev81 Without seeing any code is hard to help, but if the map works just fine my guess is that your key is not enabled for the places API. Start by verifying that on google's console.

If that's not your issue, please share some code.

**Comment by mrnickel** [comment]
I recommend replacing the `react-google-map` component with the updated `@react-google-maps/api` component.

You can then simply include the js in the script tag as you have outlined above
