### ISSUE TITLE
How to add custom placeholder

### ISSUE THREAD

**Issue by horler234** [Tintef/react-google-places-autocomplete#161]
I am having an issue adding a custom placeholder to the autocomplete input. The documentation refers to react select for styling the component but I cannot find a way to add placeholder.

**Comment by Tintef** [comment]
You need to use the `placeholder` prop of [react select.](https://react-select.com/props)

**Comment by webberwang** [comment]
Doesn't seem to work

**Comment by Tintef** [comment]
@webberwang Please send whatever you are trying and/or a repo/codesandbox to reproduce.

**Comment by mattrace** [comment]
> Doesn't seem to work

I'm having the same issue with the placeholder prop not working

**Comment by Tintef** [comment]
@mattrace  Please send whatever you are trying and/or a repo/codesandbox to reproduce.

**Comment by rahulrai123** [comment]
> Doesn't seem to work

Add placeholder inside selectProps.

`<GooglePlacesAutocomplete
              apiKey="key"
              selectProps={{
                location,
                onChange: setLocation,
                placeholder: "City, State, Country",
              }}
            />`
