### ISSUE TITLE
selectProps name underlying input onChange feature request+....

### ISSUE THREAD

**Issue by Fox4148** [Tintef/react-google-places-autocomplete#167]
The underlying input value is wrong when the onChange event is triggered.

when using 
```
selectProps={{name:'address1'}}
```

Wouldn't the component be simpler if a name would be added directly on the input we type in? I could dispatch the field value with redux.

[sandbox](https://codesandbox.io/s/react-google-places-autocomplete-selectprops-input-bug-veeh2?file=/src/App.js)

**Comment by Tintef** [comment]
@Fox4148 All the select props are passed down to an `AsyncSelect` from [react-select](https://react-select.com/).

I see that they support a `name` there, not sure if that fits your use case. But if it doesn't, you can always override their components.

**Comment by Fox4148** [comment]
I managed to fix by wrapping this component and adding a hidden react-redux Field with the value updated when onChange is triggered.
