### ISSUE TITLE
Edit address

### ISSUE THREAD

**Issue by stylesuxx** [Tintef/react-google-places-autocomplete#168]
I am wondering if it is possible to edit an already entered address - for example to add a street number.

Once autocompleted, I have to re-enter the whole address if I want to change something. Surely I must be missing something, or is this intended behavior?

**Comment by stylesuxx** [comment]
Never mind, that needs to be handled via react-select. For anyone else - this should get you going:

```js
  const [address, setAddress] = useState(null);
  const [select, setSelect] = useState(null);

  const handleFocus = (element) => {
    if (address) {
      select.select.state.inputValue = address.label;
    }
  };

  <GooglePlacesAutocomplete
    apiKey={apiKey}
    minLengthAutocomplete={3}
    autocompletionRequest={autocompletionRequest}
    selectProps={{
      ref: (ref) => {
        setSelect(ref);
      },
      value: address,
      onChange: setAddress,
      onFocus: handleFocus,
    }}
  />
```

**Comment by wickedsouls** [comment]
Somehow it does not always work :(

**Comment by siduck** [comment]
no longer works man :(
