### ISSUE TITLE
Is there a way to tell the api to always include postcode and state?

### ISSUE THREAD

**Issue by SuryaWebfox** [Tintef/react-google-places-autocomplete#169]
I've been looking at the documentation but I can't find a way to tell the API to always include the postcode and state in the results. Am I missing something?

**Comment by Tintef** [comment]
@SuryaWebfox You would have one of the geocode utility functions -- [`geocode-by-place-id`](https://tintef.github.io/react-google-places-autocomplete/docs/geocode-by-place-id) for example --.

If the given place has a postal code/state, that information will be on the geocoder response :)

Example:
```
import { useEffect, useState } from "react";
import RGPA from "react-google-places-autocomplete";
import { geocodeByPlaceId } from "react-google-places-autocomplete";

import "./styles.css";

export default function App() {
  const [value, setValue] = useState(null);

  console.log(value);

  useEffect(() => {
    if (!value) return;

    geocodeByPlaceId(value.value.place_id)
      .then((results) => console.log(results))
      .catch((error) => console.error(error));
  }, [value]);

  return (
    <div className="App">
      <RGPA
        apiKey="<RESULTS>"
        selectProps={{
          value,
          onChange: setValue
        }}
      />
    </div>
  );
}

```

**Comment by SuryaWebfox** [comment]
That works. It's a bit annoying that I first have to do a regular autocomplete, get the location ID and then perform a second call, but I understand that is a limitation of the Google API. Thanks.
