### ISSUE TITLE
Set Focus on component creation

### ISSUE THREAD

**Issue by golf-n-code** [Tintef/react-google-places-autocomplete#170]
Is is possible to set focus on the component upon render?

**Comment by SuryaWebfox** [comment]
Good point. I tried adding the `autoFocus` but it doesn't seem to work.

**Comment by Tintef** [comment]
@golf-n-code @SuryaWebfox This is technically doable by using the underlying react-select, but I think you should have a ref to it **but** the component is not exposing this ref.

I think the way to go is to add a new `selectRef` prop. PRs are welcomed!

**Comment by golf-n-code** [comment]
@Tintef I attempted to add this to the solution. Not sure if this contradicts what is happening with the forwardRef on export.

**Comment by Tintef** [comment]
@golf-n-code Actually, after thinking about it, that's doable as of now:

```
import React, { useRef } from 'react';
import RGPA from 'react-google-places-autocomplete';

const App = () => {
  const rgpaRef = useRef(null);

  const focusRGPA = () => {
    if (rgpaRef && rgpaRef.current) {
      rgpaRef.current.focus();
    }
  }

  return (
    <div className="app">
      <button onClick={focusRGPA}>
        FOCUS
      </button>
      <RGPA
        apiKey="<YOURKEY>"
        selectProps={{
          ref: rgpaRef,
        }}
      />
    </div>
  );
}

export default App;
```

cc: @SuryaWebfox
