### ISSUE TITLE
How to specify which data fields to retrieve ?

### ISSUE THREAD

**Issue by binajmen** [Tintef/react-google-places-autocomplete#174]
Hi,

Is there a way to specify which data fields to retrieve ?
https://developers.google.com/maps/documentation/places/web-service/place-data-fields

**Comment by Tintef** [comment]
@binajmen It's not currently possible, as for that you need to get the `details`.

If you use one of the provided geocode functions (see #169) you can get some fields, but not all of those.

A PR adding that is welcomed, but I'm not going to add that feature myself. I'll close the issue for now but you (or someone else) let me know if willing to implement that feature and we can reopen this issue to track that work!

**Comment by airowe** [comment]
@Tintef, is this still unsupported?

**Comment by Tintef** [comment]
Yes. PRs are welcomed.
