### ISSUE TITLE
onChange is not working in selectProps and initial value not displaying

### ISSUE THREAD

**Issue by akosijiji** [Tintef/react-google-places-autocomplete#177]
Hi there. This is my first time to use this library. I would like to get selected value from the autocomplete. This is the error message:

`Type 'Dispatch<SetStateAction<string>>' is not assignable to type '(value: OptionTypeBase | null, action: ActionMeta<OptionTypeBase>) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'OptionTypeBase | null' is not assignable to type 'SetStateAction<string>'.
      Type 'null' is not assignable to type 'SetStateAction<string>'.  TS2322`

This is what I've tried so far:

`const [address, setAddress] = useState(null);
const [inputAddress, setInputAddress] = useState("1217 Glenbrook Road, Glenbrook");

<GooglePlacesAutocomplete
                      apiKey={API_KEY}
                      selectProps={{ 
                        // placeholder: 'Search address...',
                        inputAddress,
                        address,
                        onInputChange: (newInputValue, meta) => {
                          setInputAddress(newInputValue);
                        },
                        onChange: (newValue: any, meta) => {
                          setAddress(newValue);
                          console.log('onChange', newValue)
                        }
                      }}
                    />`

Any help? I'm using React Typescript.

**Comment by Tintef** [comment]
@akosijiji Please read the docs on how to use the component, `inputAddress` and `address` are not props that can be passed down to [react-select](https://react-select.com/props).

[Here are the docs on how to save the selected result](https://tintef.github.io/react-google-places-autocomplete/docs/#save-the-selected-result).

**Comment by montagecrew** [comment]
I am also running into this error by simply doing this:
```
const [gValue, setGValue] = useState(null);

<GooglePlacesAutocomplete
    apiKey={process.env.REACT_APP_GOOGLE_PLACES_API_KEY}
    selectProps={{
        value: gValue,
	onChange: setGValue,
    }}
/>
```

Error:
![image](https://user-images.githubusercontent.com/76890735/114956446-bbf69a00-9e13-11eb-8eb0-18b01ed462c2.png)

**Comment by Tintef** [comment]
@montagecrew You can't use the setter _as-is_ while working on TS. You need to adapt set your setter function as needed or create an auxiliary function to grab what you need from react select.
