### ISSUE TITLE
componentRestrictions for country

### ISSUE THREAD

**Issue by guojuan999** [Tintef/react-google-places-autocomplete#178]
I found if I have more than five countries like below then I can't get any autocompleted address from the sixth or the seventh country "NZ" or "ZA". Just wondering if there are other settings for it? Thanks in advance. 
`autocompletionRequest={{
      componentRestrictions: {
          country:["US", "CA", "AU", "FR", "DE", "NZ", "ZA"],
       },
       types: ['geocode'],
   }}`

**Comment by Tintef** [comment]
@guojuan999 Yeah, that's a [restriction from google places library](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#ComponentRestrictions)
