### ISSUE TITLE
How can I clear the search  when I click the input field?

### ISSUE THREAD

**Issue by leevubo** [Tintef/react-google-places-autocomplete#179]
Hi, guys.

I've used this auto complete package in my google map in gatsby project and it works fine.
Now, I wanna clear the previous search string when I click the input field to enter the another location.
But its value still displays inside the text field until I enter the string.
Who knows this solution for me?
Thanks for your attention and looking forward to your reply.

https://prnt.sc/11phhap

**Comment by Tintef** [comment]
@leevubo use a controller input and set the value to null.

```
import { useEffect, useState } from "react";
import RGPA from "react-google-places-autocomplete";
import "./styles.css";

export default function App() {
  const [value, setValue] = useState(null);

  useEffect(() => {
    setValue(null);
  }, [value]);

  return (
    <div className="App">
      <RGPA
        apiKey="********"
        selectProps={{
          value,
          onChange: setValue
        }}
      />
    </div>
  );
}
```

**Comment by leevubo** [comment]
Hey, Tintef.
I've already used this code, but it didn't work onClick event.

**Comment by Tintef** [comment]
@leevubo Please share your code and/or repo/codesandbox to reproduce your error

**Comment by leevubo** [comment]
@Tintef 
Can you check this ?
https://codesandbox.io/s/sleepy-cdn-4v4gb?file=/src/pages/index.js

Sorry but replace your google key with yours.
Thanks

**Comment by Tintef** [comment]
@leevubo I wasn't able to test it yet, but from your code: 
```return (
    <Layout>
      <Seo title="Home" />
      <h1>Hi people</h1>
      <GooglePlacesAutocomplete
        apiKey=""
        selectProps={{
          placeholder: "Enter your zip code or address",
          row, // row is not a prop for react-select. This should be `value: row,`
          onChange: setRow,
          styles: {
            input: provided => ({
              ...provided,
              color: "blue"
            }),
            control: provided => ({
              ...provided,
              borderRadius: "8px"
            })
          }
        }}
      />
    </Layout>
  )```

**Comment by geekdiv** [comment]
alternative solution is you can text inside gray while menu is open which makes it look a lot better

![1](https://user-images.githubusercontent.com/12626079/118260997-9f13bc00-b4d0-11eb-8a18-3795a6e1ce4e.png)

`  <GooglePlacesAutocomplete
                    apiKey={CommonUtil.getEnv("REACT_APP_MAP_KEY")}
                    selectProps={{
                      styles: {
                        singleValue: (base, state) => ({
                          ...base,
                          color: state.selectProps.menuIsOpen
                            ? "#DCDCDC"
                            : base.color
                        })
                      }
                    }}
                  />`
