### ISSUE TITLE
disable browser autocomplete popup

### ISSUE THREAD

**Issue by jaequery** [Tintef/react-google-places-autocomplete#182]
Hi, on Chrome I am getting the browser's autocomplete suggestion popup as i type. Is there anyway to prevent this?

**Comment by Tintef** [comment]
@jaequery That would be a prop for the underlying react-select component -- I don't remember if there's a specific prop this tho --. If that doesn't exists, you can always [replace the input component](https://react-select.com/props#replacing-components)!
