### ISSUE TITLE
Restrict the return result in building level

### ISSUE THREAD

**Issue by reactching** [Tintef/react-google-places-autocomplete#183]
Hello all,

Is current version available to only return building instead of street? It is because I want to get the lat/lng of full address from user instead of region/district.

I checked that it can only set types: "address" and it can return street. can current version support it? Or do it have any workaround?

Thanks all. I have already tried for whole day.

**Comment by Tintef** [comment]
@reactching Yeah, the only available options are the ones [that google provide](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest) and I don't seem to see the option you want.
