### ISSUE TITLE
How to get the Place ID from the GooglePlacesAutocomplete component

### ISSUE THREAD

**Issue by jorgerubik** [Tintef/react-google-places-autocomplete#184]
Hello, I am using the Google Places Autocomplete component, I see that the value is saved as an object, but I cannot reach the place ID and then occupy your function that you send that edata and it returns the coordinates

**Comment by Tintef** [comment]
@jorgerubik I'm not sure I'm understanding your question, the key for the place ID is `place_id` (yes, in snakecase).

fyi: I see you speak Spanish, feel free to ask in Spanish if you prefer.

**Comment by jorgerubik** [comment]
Hola, ok, espero poderme dar a entender mejor en español.

Lo que intento hacer es primero colocar el buscador que tienes de direcciones, el cual ya me funciona.
De ahí lo que busco es con la dirección seleccionada obtener el place ID del objeto y ese mandarlo a tu método que regresa las coordenadas por medio de place ID.

Saludos!

**Comment by Tintef** [comment]
@jorgerubik Lo que quieres es usar la componente [de este forma](https://tintef.github.io/react-google-places-autocomplete/docs/examples#controlled-input). Luego, puedes usar un `useEffect` para obtener el `place_id` y llamar a la función [geocodeByPlaceId](https://tintef.github.io/react-google-places-autocomplete/docs/geocode-by-place-id/)

**Comment by jorgerubik** [comment]
Si, justo eso es lo que estoy intentando hacer, pero en el useEffect no me permite obtener el placeId, siempre me dice que value puede venir null y me da error
