### ISSUE TITLE
No Options

### ISSUE THREAD

**Issue by davidbarman** [Tintef/react-google-places-autocomplete#186]
After including in my project, I am just getting a dropdown selector that says No Options.  There doesn't appear to be a way to search, etc.  I've tried getting basic as:

`<GooglePlacesAutocomplete
      apiKey="****"
    />`

I assume I must be doing something wrong?   Any suggestions?

**Comment by Tintef** [comment]
@davidbarman Is your `apiKey` enbaled for the places API? What about the allowed domains to use the key?

**Comment by davidbarman** [comment]
> @davidbarman Is your `apiKey` enbaled for the places API? What about the allowed domains to use the key?

The apiKey is enabled in the Google account.  I checked the API setting and Application Restrictions are set to none.  Don't see anywhere else about adding allowed domains.

**Comment by Tintef** [comment]
@davidbarman Is the places API listed in the API Restrictions?

<img width="807" alt="Screen Shot 2021-05-05 at 10 59 12" src="https://user-images.githubusercontent.com/17990217/117152997-ee4f4380-ad90-11eb-9ca0-210c6c582f3a.png">

**Comment by davidbarman** [comment]
Under API restrictions, it is set to don't restrict key.  After selecting the restrict option and checking the Places API, still not change in the React application.

**Comment by Tintef** [comment]
@davidbarman Do you have `window.google.maps` available on your browser console?

**Comment by davidbarman** [comment]
Yes, it exists.

**Comment by Tintef** [comment]
🤔 that's weird. Can you share your code?

**Comment by davidbarman** [comment]
`import GooglePlacesAutocomplete from "react-google-places-autocomplete";


<GooglePlacesAutocomplete
                  apiKey="****"
                  placeholder="Type in an address"
                  inputStyle={{
                    height: 40,
                    fontSize: 28,
                  }}
                  suggestionsStyles={{
                    container: {
                      padding: 16,
                      background: "#efefef",
                    },
                    suggestion: {
                      background: "#eee",
                      cursor: "pointer",
                    },
                    suggestionActive: {
                      background: "#bbb",
                    },
                  }}
                />`

**Comment by Tintef** [comment]
@davidbarman You're using 2.x?

**Comment by davidbarman** [comment]
v3.3.0

**Comment by davidbarman** [comment]
If I try:
`<GooglePlacesAutocomplete
apiKey="****" />
`

It does the same thing.

**Comment by Tintef** [comment]
@davidbarman You're missing something on the api key configuration, but I'm not sure what. Please review google docs on how to set it up. This code works well for me with a valid api key:

```
import RGPA from "react-google-places-autocomplete";

export default function App() {
  return (
    <div className="App">
      <RGPA apiKey="" />
    </div>
  );
}
```
