### ISSUE TITLE
Access list of results/Select first result suggestion on Enter

### ISSUE THREAD

**Issue by Calfredop** [Tintef/react-google-places-autocomplete#187]
Hello,
First of all thanks for this amazing component. I would like to simplify the address entry process, by letting the user to pick the first suggestion on Enter press. I've seen other resolved issues with onKeyDown ovveride of input, but none of them reffered to a way to access the results/suggestions list. In other words, how can I call onSelect with a specific picked suggestion (in this case the first)?

Thank you very much

**Comment by Tintef** [comment]
@Calfredop React-select handles this by default (selecting the first option on Enter press). If you want to get the selected suggestion, you should use it as [controlled input](https://tintef.github.io/react-google-places-autocomplete/docs/#save-the-selected-result).

If this doesn't work for you, please share your code and/or a sandbox/repo to reproduce and I can take a closer look.

**Comment by Tintef** [comment]
@Calfredop What's preventing you from migrating to 3.x?

I don't remember how 2.x worked to be honest, but as you are using a custom input shouldn't you handle the `onPressDown` there?

**Comment by Calfredop** [comment]
I could handle onKeyDown but it seems there are no way to reacht suggestion list from there. I'll migrate to v3 if there are no other options 🤷 
Thank you very much for your response

**Comment by Tintef** [comment]
@Calfredop Yeah, I was taking a look at the code from 2.3.2 and it doesn't seem to be a way of doing it. It's simple enough to change the code to support it you want to -- maybe you can work on your own fork from 2.3.2 and build from there --.

I would recommend you to migrate to 3.x tho, [here is the migration guide](https://tintef.github.io/react-google-places-autocomplete/docs/v2-to-v3/)
