### ISSUE TITLE
There's no prop for the className or style

### ISSUE THREAD

**Issue by fkgfahad** [Tintef/react-google-places-autocomplete#193]

**Comment by Tratt0re** [comment]
Hi, you can do that by passing the "selectProps".
This library uses as main component the "asyns selector" of react-select so if you need to change or pass any value you can do it by passing props to selectProps. 

```
<GooglePlacesAutocomplete
    apiKey="APIKEY"
    selectProps={{
          className: "react-select",
          classNamePrefix: "react-select"
     }}
/>
```

**Comment by Tintef** [comment]
Thanks @Tratt0re

**Comment by fkgfahad** [comment]
Thanks, @Tratt0re. Although at least a dedicated style prop and a className prop are very useful.
I think it is not a good practice at all.

**Comment by Tintef** [comment]
@fkgfahad I strongly disagree.

Why should the library re-implement what the underlying `react-select` already provides?
Why do you think it's not a good practice?
