### ISSUE TITLE
Load Google Core API lazily?

### ISSUE THREAD

**Issue by rturk** [Tintef/react-google-places-autocomplete#2]
Hi it is possible to load Google API lazily or pragmatically?

I have a React App and I only need this features in a few pages/routes of my code, loading it on all pages is unnecessary

`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_GOOGLE_API_KEY&libraries=places"></script>`

**Comment by Tintef** [comment]
@rturk Sorry for the late response.

As you can see here: https://github.com/Tintef/react-google-places-autocomplete/blob/d9bd68c28745de12fc6ac74778f335c89e8c5a95/src/GooglePlacesAutocomplete/index.js#L61

The component calls a `setTimeout` until google API is successfully loaded, so you could programmatically add the `script` tag in the pages/routes you need and it should work (haven't tested it).

Let me know if this works or if you need any help!

**Comment by Tintef** [comment]
Closed for lack of response.
