### ISSUE TITLE
Random typescript error when trying to get lat lng from zip code

### ISSUE THREAD

**Issue by ataravati** [Tintef/react-google-places-autocomplete#201]
I've written a function like below to get LatLng from Zip Code. It works once in a while, but then suddently it gives me the following error. When I start getting the error, it will never go away, until I make a change (and I don't know what) and it starts working again.

>TypeError: Cannot read property 'location' of undefined

```
const zipCodeToLatLng = async (zipCode: string) => {
    const geocoderResult = {
      address_components: [
        {
          long_name: zipCode,
          short_name: zipCode,
          types: ["postal_code"],
        },
      ],
    };

    try {
      const latLng = await getLatLng(geocoderResult as any);
      const position = {
        lat: latLng.lat,
        long: latLng.lng,
      };

      return position;
    } catch (err) {
      console.log(err);
    }

    return null;
  };
  ```

**Comment by ataravati** [comment]
Sorry! My bad; I didn't have the google places api on the page.

**Comment by rimpu** [comment]
Hi @ataravati 

How did you bring google places api  on your page or how did you load I mean ?
