### ISSUE TITLE
Geocode by Address TypeError 

### ISSUE THREAD

**Issue by nmsdvid** [Tintef/react-google-places-autocomplete#204]
Hello I would like to use the geocodeByAddress api but it returns the following error:
`Uncaught (in promise) TypeError: Cannot read property 'maps' of undefined`

Example of usage:
```
    geocodeByAddress('Bratislava, Slovakia')
    .then(results => console.log(results))
    .catch(error => console.error(error));
```
Version: 3.3.1

Any ideas?

**Comment by Tintef** [comment]
@nmsdvid Looks like the google places API is not loaded.

If you only want to use the util function (without using the component) you still need to include the google places api
