### ISSUE TITLE
Bump `react-select` version up to fix emotion/cache import error

### ISSUE THREAD

**Issue by jmaslin** [Tintef/react-google-places-autocomplete#206]
There is an issue with this version of `react-select` that breaks when used with Chakra UI. It seems to be fixed in `v4.3.1` according to https://github.com/JedWatson/react-select/issues/4541

Additional context:
https://github.com/emotion-js/emotion/issues/2343

Can we bump the version up to fix this? Thank you!

**Comment by jmaslin** [comment]
Actually looks like `4.3.1` is being included in my `yarn.lock` file so don't think that will fix it. Anyone run into this?

**Comment by Tintef** [comment]
@jmaslin This could actually be on this repo as react-select is a dependency on the repo (not a peer dep).

I can release an updated version as an alpha version and you can verify it works as expected using it?

**Comment by jmaslin** [comment]
@Tintef that would be great, thank you! I am using `react-select` in other parts of the app and it works as expected

**Comment by Tintef** [comment]
@jmaslin You should be able to install the new version (`npm i react-google-places-autocomplete@3.3.2-alpha.0`).

Let me know how it goes!

**Comment by jmaslin** [comment]
@Tintef It seems to be working on dev and build versions, thank you! I will let you know if I encounter any other issues.

**Comment by Tintef** [comment]
@jmaslin Awesome! I'll try to gather some time this week to merge the change and publish a new version :)

**Comment by javiercejudo** [comment]
Looking forward to this. To add more context, this was causing problems in a project that uses `react-select` directly in conjunction with this project. Anyone using react-select < 4.3.1 directly could run into this issue even after this update, but at least once they upgrade, everything should work well.

**Comment by Tintef** [comment]
@javiercejudo Yeah, I'm aware of that. I'm having a hard time on finding some time to merge, publish and test.

I hope to have time over this weekend :)

**Comment by Tintef** [comment]
Released on v3.3.2

cc: @javiercejudo
