### ISSUE TITLE
Missing name prop

### ISSUE THREAD

**Issue by gperez-10pines** [Tintef/react-google-places-autocomplete#208]
I'm curious why the `name` prop is not available. As a form field, I think it should be part of `GooglePlacesAutocompleteProps`.

I'm getting a typescript warning because it's not:

> GooglePlacesAutocompleteProps & RefAttributes<GooglePlacesAutocompleteHandle>'.   Property 'name' does not exist on type 'IntrinsicAttributes & GooglePlacesAutocompleteProps & RefAttributes<GooglePlacesAutocompleteHandle>'.

**Comment by Tintef** [comment]
@gperez-10pines This library relies on [react-select](https://react-select.com/props), you should pass props to it.

You can check how [here](https://tintef.github.io/react-google-places-autocomplete/docs/props).
