### ISSUE TITLE
How Do You Set The Initial Value?

### ISSUE THREAD

**Issue by rossm6** [Tintef/react-google-places-autocomplete#213]
I have -

```
  <GooglePlacesAutocomplete
      apiKey={'someKey'}
      autocompletionRequest={{
          componentRestrictions: {
              country: ['uk']
          }
      }}
      selectProps={{
          value: address,
          onChange: (o) => {
              let placeId = o["value"]["place_id"];
              setAddress(o);
              formik.setFieldValue("googlePlaceId", placeId);
          }
      }}
  />
```

What do I need to pass as the value of "address" for there to be an initial value?

I've tried {label: "some address", place_id: "ChIJNYiUp8ROeEgRikq4Ws76OpU"} and passing the object returned by using the utility geocodeByPlaceId.  The former works in so far has it shows the label in the input field upon initialisation but it appears broken.  For example when I try and delete the value with backspace my react app crashes with this error in the console -

```
Uncaught TypeError: Cannot read property 'place_id' of undefined
    at Object.getOptionValue (index.es.js:30)
    at cr (index.es.js:30)
    at eval (index.es.js:30)
    at Array.some (<anonymous>)
    at lr (index.es.js:30)
    at or (index.es.js:30)
    at eval (index.es.js:30)
    at Array.map (<anonymous>)
    at rr (index.es.js:30)
    at eval (index.es.js:30)
```

Question on SO - https://stackoverflow.com/questions/68755252/is-there-a-way-to-set-the-initial-value-for-react-google-places-autocomplete

**Comment by Tintef** [comment]
@rossm6 glad you were able to figure it out.

The library is plug in when doing basic stuff. But once you want to start customizing it does get a bit more complex.

It's also impossible for me to document every possible use case for this library -- although I agree setting the default value is pretty common, but it's well explained on react-select docs --.

Anyway, a PR adding examples is always welcomed.
