### ISSUE TITLE
Ensure CORS response header values are valid

### ISSUE THREAD

**Issue by usamamashkoor** [Tintef/react-google-places-autocomplete#227]
The autocomplete works fine when we refresh the page, but when I navigate to the different react pages and then I type something to the autocomplete then I get this error

**Ensure CORS response header values are valid**

and then the autocomplete does not show me anything, If I refresh the page again, then the autocomplete again works fine.

Can anyone help me with this issue?

This is my code

```
<GooglePlacesAutocomplete
    apiKey={'my key'}
    minLengthAutocomplete={8}
    selectProps={{
        placeholder: 'Enter Your Address',
        value: objQueryData,
        onChange: handleOnChangeLocation,
        className:`form-control react-select-container`,
        classNamePrefix:"react-select",
    }}
/>
```

**Comment by Tintef** [comment]
@usamamashkoor Please provide somehow to reproduce this issue, as I have never seen it. Also, how are you hosting your site?

**Comment by Tintef** [comment]
Might also be something on the configuration of your Google places API key! IIRC there's a section of allowed domains 🤔

**Comment by Tintef** [comment]
Closing due to lack of response

**Comment by dhruvbhatia7** [comment]
Facing this same issue. Can someone please help?
