### ISSUE TITLE
input text area width show less when i go for update 

### ISSUE THREAD

**Issue by plentys-interns** [Tintef/react-google-places-autocomplete#229]
![googlePlaceAutoComplete](https://user-images.githubusercontent.com/69135055/140469616-00218d00-2e04-4b5e-9091-f5f3331affd0.PNG)

i select address and submit and when i again reopen tab  for update address the text area width get small thast why text get hidden how to reslove this issue i even try with option value style

**Comment by Tintef** [comment]
@plentys-interns Provide a repository to reproduce your issue or a codesandbox.

**Comment by Tintef** [comment]
Closing from lack of response
