### ISSUE TITLE
Placeholder not clearing on focus

### ISSUE THREAD

**Issue by PaperjetStudios** [Tintef/react-google-places-autocomplete#230]
Hey there, how would I achieve this - when I click on the select bar with a placeholder, the typing cursor shows at the end of the placeholder, when I start typing it clears, but the cursro at the end of the placeholder is confusing some people.

**Comment by Tintef** [comment]
@PaperjetStudios that's weird. I have never seen that happening with react-select. Can you provide a reproduce-able example?

**Comment by Tintef** [comment]
Closing from lack of response
