### ISSUE TITLE
How to sync up input with active suggestion while navigating through suggestions using arrow key?

### ISSUE THREAD

**Issue by yh10106699** [Tintef/react-google-places-autocomplete#231]
My initial thought is to update the address state in the `renderSuggestions` props as that's where I can get the info about active suggestion and suggestion results. However, this prevents you from changing the input while you are navigating the suggestions. Another problem is that this gives the warning `Cannot update a component while rendering a different component`. Then I tried to wrap the logics in a component and return it in the  `renderSuggestions`. This works fine, but it will call the api whenever we navigate through the results using arrow keys because the state `active` is changing, which will trigger the re-render. Is there any alternative on this problem or am I missing something here?

**Comment by yh10106699** [comment]
As I am using the controlled the input, when input value change, the component would fire a new request for the places result. How can I avoid that like the google search?

**Comment by Tintef** [comment]
@yh10106699 I'm not sure I understand what issue you're facing, please provide a repo to reproduce your issue.

As for your second question, there might be a way to accomplish what you want inside [react-select Async select](https://react-select.com/async#loading-asynchronously), but I don't know if it's actually possible.

**Comment by Tintef** [comment]
Closing from lack of response
