### ISSUE TITLE
Missing zip codes

### ISSUE THREAD

**Issue by hope-portal-services** [Tintef/react-google-places-autocomplete#233]
Why are postal codes not returned in the response? Seems like a fairly common piece of data to have included.

**Comment by Tintef** [comment]
@hope-portal-services the response is not from this library, that comes from [google places API](https://developers.google.com/maps/documentation/places/web-service/overview).

I'm guessing that you can get the postal code after selecting an address by using [geocodeById](https://tintef.github.io/react-google-places-autocomplete/docs/geocode-by-place-id) (haven't tested it).
