### ISSUE TITLE
can i use react-select library when RGPA already installed in my project? 

### ISSUE THREAD

**Issue by MuhammadAlbab** [Tintef/react-google-places-autocomplete#235]
i get this warning when try to use react-select library with RGPA already installed in my project.
"You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used."

**Comment by Tintef** [comment]
@MuhammadAlbab which version are you using? AFAIK that's fixed on v3.3.2 (see [#206](https://github.com/Tintef/react-google-places-autocomplete/issues/206))

**Comment by MuhammadAlbab** [comment]
i found this link, i think i face the same problem as this dude here: [](https://githubmemory.com/repo/Tintef/react-google-places-autocomplete/issues/176)

```
"react-google-places-autocomplete": "^3.3.2",
"react-select": "^5.2.1"
```

**Comment by Tintef** [comment]
Huh, sadly that's outside of the scope of this library 🥺.

**Comment by andreasciamanna** [comment]
Can't `react-select` be set as peerDependencies?
