### ISSUE TITLE
Works first couple or three times but then hangs...

### ISSUE THREAD

**Issue by davidlehrian** [Tintef/react-google-places-autocomplete#243]
Hello,
Thanks for releasing this great component. I'm having a small issue with it and was hoping you might be able to shed some light on it. I have installed the component via NPM and have included the googleapis script as:

`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=MY_API_KEY&libraries=places"></script>`

and I included the component on a page via:

```
import React, { useState } from 'react'
import GooglePlacesAutocomplete from 'react-google-places-autocomplete'

export const LocationSearchInput = () => {
  const [value, setValue] = useState(null);
  return (
    <div>
      <GooglePlacesAutocomplete />
    </div>
  );
}
```

The component shows up on my page and I can start typing and it provides me some options of places.  I can select one and it is selected.  Then I do it a second time and it seems to work, but when I try a third time it just hangs with the three dots on the right of the component showing it is trying to do something.  I never see a third request made to Google.  It eventually times out and goes back to the previously selected location. I have tried both Google Chrome and Mozilla Firefox and get the same result.  Just curious is maybe I have the wrong version of React installed or something.  Here is my package.json.

```
{
  "name": "frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "webpack --mode development --entry ./src/index.js --output-path ./static/frontend",
    "build": "webpack --mode production --entry ./src/index.js --output-path ./static/frontend"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.16.12",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7",
    "babel-loader": "^8.2.3",
    "css-loader": "^6.5.1",
    "source-map-loader": "^3.0.1",
    "style-loader": "^3.3.1",
    "webpack": "^5.67.0",
    "webpack-cli": "^4.9.2"
  },
  "dependencies": {
    "axios": "^0.25.0",
    "bootstrap": "^5.1.3",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-bootstrap": "^2.1.1",
    "react-dom": "^17.0.2",
    "react-google-places-autocomplete": "^3.3.2",
    "react-router-bootstrap": "^0.26.0",
    "react-router-dom": "^6.2.1"
  }
}
```

**Comment by alia-peterson** [comment]
I'm not positive since I'm not part of the dev team, but I think you need to add your value and setValue as select props.

Try:
```
<GooglePlacesAutocomplete 
  selectProps={{
    value,
    onChange={setValue},
  }}
/>
```

**Comment by davidlehrian** [comment]
That is to get the selected value, but I was keeping it as the simplest example that is provided here:

https://www.npmjs.com/package/react-google-places-autocomplete

This just displays the component and performs type ahead matching.

**Comment by davidlehrian** [comment]
It seems that a clock component on the same page that was using the useEffect hook to watch its 'date' state via
```
	useEffect(() => {
		setInterval(() => setDate(new Date()),1000);
	},[date]);
```
was causing the search component to hang after two or three searches. I changed the effect to watch [] instead of [date] 

```
	useEffect(() => {
		setInterval(() => setDate(new Date()),1000);
	},[]);
```

and the autocomplete component installed further down on the same page started working consistently. But now I'm even more confused as I don't understand how 2 completely independent components on the same page can impact each other's operation. But that is not this project's issue as the autocomplete component does now seem to be working as advertised so I will be closing this issue.
