### ISSUE TITLE
Not able to use defaultInputValue prop

### ISSUE THREAD

**Issue by alia-peterson** [Tintef/react-google-places-autocomplete#244]
Trying to use the component for locations that may already have a saved address. When I pass a string through the `defaultInputValue` react-select prop, no text is displayed in the input and the div (class "css-xxxxxx-selectValue") that is created when an address is selected is not present. 

My component looks like this:

```
const [formattedAddress, setFormattedAddress] = useState('')

useEffect(() => {
  setFormattedAddress(address)
}, [address]);
// address is a prop coming from the parent component

return (
  <div>
    <GooglePlacesAutocomplete
      selectProps={{
        formattedAddress,
        onChange: handleAddressChange,
        isClearable: true,
        defaultInputValue: formattedAddress,
      }}
    />
  </div>
)
```

**Comment by Tintef** [comment]
@alia-peterson The issue you are facing is that `formattedAddress` is an empty in the first render of your component, so react-select uses that as the `deafultInputValue` and it doesn't change when formattedAddress changes.

If you want the select component to react to `formattedAddress` change you should that string as the `inputValue` value and use `onInputChange` to control it :)

Something like this:
````
import { useState, useEffect } from "react";
import GPA from "react-google-places-autocomplete";

const Comp = ({ address, handleAddressChange = console.log }) => {
  const [formattedAddress, setFormattedAddress] = useState("Test");

  useEffect(() => {
    setFormattedAddress(address);
  }, [address]);

  return (
    <div>
      <GPA
        apiKey="<YOUR_KEY>"
        selectProps={{
          onChange: handleAddressChange,
          isClearable: true,
          inputValue: formattedAddress,
          onInputChange: setFormattedAddress,
        }}
      />
    </div>
  );
};
```

Hope this helps!

**Comment by alia-peterson** [comment]
@Tintef you're a life saver, thanks!
