### ISSUE TITLE
Getting an error: ERROR in ./node_modules/react-google-places-autocomplete/build/index.es.js 

### ISSUE THREAD

**Issue by maks1mp** [Tintef/react-google-places-autocomplete#252]
ERROR in ./node_modules/react-google-places-autocomplete/build/index.es.js 1509:9-29
export 'useInsertionEffect' (imported as 'e') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
 @ ./src/GoogleMapsLocation.tsx 8:0-111 64:28-44 90:8-23 118:44-68 188:46-62
 @ ./src/index.tsx 6:0-52 10:33-51

**Comment by Tintef** [comment]
@maks1mp Please provide a repro to reproduce, or at least how you are using the component + the versions of your packages.

**Comment by Tintef** [comment]
Closing due to lack of response.
