### ISSUE TITLE
Is there a way to add ```strictBounds``` parameter to autocompletionRequest ?

### ISSUE THREAD

**Issue by ajeffika** [Tintef/react-google-places-autocomplete#260]
Hi, is there a way to add that parameter? Bounds are already there and it would be beneficial for searching within a given cooridinates.

**Comment by lorenzolaricchia** [comment]
You can't.
But you can use the filterOption prop to filter strictly your options based on bounds.
The problem is that filterOption can't be async, so you the answer to your question is NO 😅, but I think you can find a shortcut to handle this.

```
selectProps={{
   ...,
   filterOption: async (option, inputValue) => {
       const geocodedResults = await geocodeByPlaceId(option.value.place_id)
       const location = geocodedResults[0].geometry.location
       const optionBounds = {
          lat: location.lat(),
          lng: location.lng()
       }
      
       return isInsideBounds(myBounds, optionBounds)
   },
}}
```

**Comment by Tintef** [comment]
Yep, that doesn't seem to be an option for the `autocompletionRequest` (see [here](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest)).
