### ISSUE TITLE
defaultOptions not working

### ISSUE THREAD

**Issue by vernu** [Tintef/react-google-places-autocomplete#261]
Hello,
I'm trying to add defaultOptions in the select, but it doesn't seem to work and It shows no options.
Here's my code:
`<GooglePlacesAutocomplete
          selectProps={{
            value,
            onChange: setValue,
            defaultOptions: options,
          }}
          apiKey={process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY}
        />`

**Comment by lorenzolaricchia** [comment]
`react-select` has only the `options` prop available [docs](https://react-select.com/props).
You need the Async version [docs](https://react-select.com/async) of the component, that I think react-google-places-autocomplete does not support.

**Comment by kexposito** [comment]
@vernu could you share how your options looks?
you should have something like:
```
const popularCities = [
  { value: 'Austin, TX, USA', label: 'Austin, TX, USA'}
];

<GooglePlacesAutocomplete
  selectProps={{
    ...
    defaultOptions: popularCities,
    ...
 }}
/>

```

**Comment by vernu** [comment]
> @vernu could you share how your options looks?
> you should have something like:
> ```
> const popularCities = [
>   { value: 'Austin, TX, USA', label: 'Austin, TX, USA'}
> ];
> 
> <GooglePlacesAutocomplete
>   selectProps={{
>     ...
>     defaultOptions: popularCities,
>     ...
>  }}
> />
> 
> ```
> 
> Use `value` and `label` in your options

Yes that's exactly what im using.

**Comment by Tintef** [comment]
Let's recap on a couple things:

- @lorenzolaricchia: react-google-places-autocomplete does use Async from react-select!
- As @kexposito said, you need to have something like `[{ value: 'Austin, TX, USA', label: 'Austin, TX, USA'}]` as the `defaultOptions`, you can see it working [here](https://codesandbox.io/s/boring-fermi-6nkt48)
