### ISSUE TITLE
Is there a way to get individual values for streetno, street name, city, country, pincode once user selects a value from the autocomplete search

### ISSUE THREAD

**Issue by rimpu** [Tintef/react-google-places-autocomplete#262]
Hi,

I see when we select a value from the dropdown we get the following list.
{
    "label": "Uenuku Way, Auckland Airport, Auckland, New Zealand",
    "value": {
        "description": "Uenuku Way, Auckland Airport, Auckland, New Zealand",
        "matched_substrings": [
            {
                "length": 3,
                "offset": 0
            }
        ],
        "place_id": "EjNVZW51a3UgV2F5LCBBdWNrbGFuZCBBaXJwb3J0LCBBdWNrbGFuZCwgTmV3IFplYWxhbmQiLiosChQKEgkDUWVHwk8NbRFpl2IHSbNr7hIUChIJR3FA2uZPDW0RxoB00urZ5wM",
        "reference": "EjNVZW51a3UgV2F5LCBBdWNrbGFuZCBBaXJwb3J0LCBBdWNrbGFuZCwgTmV3IFplYWxhbmQiLiosChQKEgkDUWVHwk8NbRFpl2IHSbNr7hIUChIJR3FA2uZPDW0RxoB00urZ5wM",
        "structured_formatting": {
            "main_text": "Uenuku Way",
            "main_text_matched_substrings": [
                {
                    "length": 3,
                    "offset": 0
                }
            ],
            "secondary_text": "Auckland Airport, Auckland, New Zealand"
        },
        "terms": [
            {
                "offset": 0,
                "value": "Uenuku Way"
            },
            {
                "offset": 12,
                "value": "Auckland Airport"
            },
            {
                "offset": 30,
                "value": "Auckland"
            },
            {
                "offset": 40,
                "value": "New Zealand"
            }
        ],
        "types": [
            "route",
            "geocode"
        ]
    }
}

is there a way to be more specific which offset value is what, like which one will be the street name or number or city?
because currently based on the string searched we can get different results for the terms array. And is there a pattern followed like the last value in terms array it always refers to the country, second last as the city ?

**Comment by lorenzolaricchia** [comment]
You have to call `geocodeByPlaceId(placeId)` and look inside `address_components` of item 0 (Google Maps Geocoding API is required).

**Comment by rimpu** [comment]
worked!!

**Comment by Tintef** [comment]
Thanks @lorenzolaricchia!!
