### ISSUE TITLE
result filter option

### ISSUE THREAD

**Issue by perochak** [Tintef/react-google-places-autocomplete#263]
Do we have option to filter the results as per need?
Like I want to filter the results to show if there is zipcode.

**Comment by lorenzolaricchia** [comment]
You can only use the `filterOption` prop, that filters the options given from the react-google-places-autocomplete result.

```
selectProps={{
   ...,
   filterOption: (option, inputValue) => {
      // return hasZipCode(option)
      return true
   },
}}
```

**Comment by Tintef** [comment]
Thanks @lorenzolaricchia for the reply, I'm gonna close this one.
