### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'maps')

### ISSUE THREAD

**Issue by rimpu** [Tintef/react-google-places-autocomplete#264]
Hi,
I am using the below react code to populate a default value when the google autocomplete loads for the first time. But I am getting an error. Could someone take a look and let me know when I am wrong?

The error is being thrown at "geocodeByPlaceId("ChIJH_imbZDuDzkR2AjlbPGYKVE")"

import "./styles.css";
import GooglePlacesAutocomplete, {
  geocodeByPlaceId
} from "react-google-places-autocomplete";
import React, { useState, useEffect } from "react";

export default function App() {
  const [address, setAddress] = useState({
    label: "",
    value: {
      place_id: ""
    }
  });

  useEffect(() => {
    console.log("On mount");
    geocodeByPlaceId("ChIJH_imbZDuDzkR2AjlbPGYKVE")
      .then((results) => {
        console.log(results);
        setAddress({
          label: results[0].formatted_address,
          value: {
            place_id: ""
          }
        });
      })
      .catch((error) => console.error(error));
  }, []);

  console.log(address);
  return (
    <div className="App">
      <GooglePlacesAutocomplete
        apiKey="*******************************"
        autocompletionRequest={{
          componentRestrictions: {
            country: []
          },
          types: ["address"]
        }}
        minLengthAutocomplete={3}
        selectProps={{
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          // onChange: (place) => {
          //   console.log(place);
          //   setAddressText(place.label)
          // },
          value: address,
          classNamePrefix: "Select"
        }}
      />
    </div>
  );
}

**Comment by lorenzolaricchia** [comment]
When you call geocodeByPlaceId() GooglePlacesAutocomplete has not been loaded.

**Comment by rimpu** [comment]
How to make sure that we call only after GooglePlacesAutocomplete is loaded, any idea?

**Comment by lorenzolaricchia** [comment]
I think geocodeBy*() utility functions should be used in combo with the autocomplete component, like with the onChange() method.

**Comment by rimpu** [comment]
Ok, yes that works fine when used geoCodeBy* with onChange. But I will need to prepopulate the value soon after the component mounts, is there a way to do so?

**Comment by lorenzolaricchia** [comment]
```
const [token, setToken] = useState<google.maps.places.AutocompleteSessionToken>()
const autocompleteRef = useRef<GooglePlacesAutocompleteHandle>(null)

useEffect(() => {
    if (!autocompleteRef.current) {
      return
    }
    setToken(autocompleteRef.current.getSessionToken())
  }, [autocompleteRef])

  useEffect(() => {
    if (!token) {
      return
    }
    geocodeByPlaceId('ChIJH_imbZDuDzkR2AjlbPGYKVE').then(console.log).catch(console.error)
  }, [token])
  
  return <GooglePlacesAutocomplete ref={autocompleteRef} ... />
```

**Comment by Tintef** [comment]
@rimpu Another options is to manually load the google places api script instead of relying on the component to load it for you!
