### ISSUE TITLE
How to unit test geocodeByPlaceId in jest ?

### ISSUE THREAD

**Issue by rimpu** [Tintef/react-google-places-autocomplete#265]
Hi,
I am using a  react component and trying to test the geocodeByPlaceId method using react testing library/ jest.
Below is my code which is used to prepopulate an address if place_id is supplied.
But unfortunately, when I am trying to test this functionality by providing a place_id, it does not call the geocodeByPlaceId method

```
useEffect(() => {
    const savedPlaceID = getValues('place_id') || '';
    (async () => {
      try {
        if (savedPlaceID !== '') {
          console.log(savedPlaceID, geocodeByPlaceId);
          await geocodeByPlaceId(savedPlaceID) // While testing it is not going inside this function
            .then((results) => {
              **console.log(results); // This line is not getting printed**
              setValue(`${prefixName}.place_id`, results[0].place_id || '');
              setAddress({
                label: results[0].formatted_address,
                value: {
                  description: results[0].formatted_address,
                  place_id: savedPlaceID,
                },
              });
            })
            .catch((error) => console.error(error));
        }
      } catch (e) {
        console.log(console.error(e));
      }
    })();
  }, []);
```
  
  In setuptests I have defined the following :
  
  ```
beforeAll(() => {
  type Suggestions = google.maps.places.AutocompletePrediction[] | null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const getMaps = (type = 'success', data: Suggestions): any => ({
    maps: {
      places: {
        AutocompleteService: jest.fn(() => ({
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          getPlacePredictions: (_: any, cb: (dataArg: Suggestions) => void) => {
            setTimeout(() => {
              cb(type === 'success' ? data : null);
            }, 500)
          },
        })),
        AutocompleteSessionToken: jest.fn(),
      },
      Geocoder: jest.fn().mockImplementation(() => {
        return {
          geocode: jest.fn().mockResolvedValue({
            results:[
              {
                'address_components': [
                  {
                    'long_name': 'Chester Square',
                    'short_name': 'Chester Square',
                    'types': [
                      'route',
                    ],
                  },
                  {
                    'long_name': 'London',
                    'short_name': 'London',
                    'types': [
                      'postal_town',
                    ],
                  },
                  {
                    'long_name': 'Greater London',
                    'short_name': 'Greater London',
                    'types': [
                      'administrative_area_level_2',
                      'political',
                    ],
                  },
                  {
                    'long_name': 'England',
                    'short_name': 'England',
                    'types': [
                      'administrative_area_level_1',
                      'political',
                    ],
                  },
                  {
                    'long_name': 'United Kingdom',
                    'short_name': 'GB',
                    'types': [
                      'country',
                      'political',
                    ],
                  },
                  {
                    'long_name': 'SW1W',
                    'short_name': 'SW1W',
                    'types': [
                      'postal_code',
                      'postal_code_prefix',
                    ],
                  },
                ],
                'formatted_address': 'Chester Square, London SW1W, UK',
                'geometry': {
                  'bounds': {
                    'south': 51.49382059999997,
                    'west': -0.1515979,
                    'north': 51.49660750000002,
                    'east': -0.1480092,
                  },
                  'location': {
                    'lat': 51.4953752,
                    'lng': -0.1491993,
                  },
                  'location_type': 'GEOMETRIC_CENTER',
                  'viewport': {
                    'south': 51.49382059999997,
                    'west': -0.1515979,
                    'north': 51.49660750000002,
                    'east': -0.1480092,
                  },
                },
                'place_id': 'EhpDaGVzdGVyIFNxdWFyZSwgTG9uZG9uLCBVSyIuKiwKFAoSCc9N1IoiBXZIEcSWVQeGqXytEhQKEgnz8xe3Wxt2SBEKsgA5eS6RSQ',
                'types': [
                  'route',
                ],
              },
            ],
          }),
        };
      }),
    },
  });

  global.google = getMaps('success', []);
})
```
  
 Any help will be highly appreciated.

**Comment by ashish-eeposit** [comment]
mock the component and use as follow : 
jest.mock('react-google-places-autocomplete', () => ({
  __esModule: true,
  geocodeByPlaceId: jest.fn(
    () =>
      new Promise((resolve) => {
        resolve([
          {
            address_components: [
              {
                long_name: 'long_name',
                short_name: 'short_name',
                types: ['administrative_area_level_1'],
              },
              {
                long_name: 'long_name',
                short_name: 'short_name',
                types: ['locality', 'political'],
              },
              {
                long_name: 'long_name',
                short_name: 'short_name',
                types: ['country', 'political'],
              },
            ],
          },
        ]);
      }),
  ),
  getLatLng: jest.fn().mockRejectedValueOnce(new Error('Error')).mockResolvedValue({ lat: 0, lng: 0 }),

  // eslint-disable-next-line react/display-name
  default: (
    props: React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement> & {
      selectProps: { onChange: (value: GoogleAutoCompleteValues) => void };
    },
  ) => (
    <input
      data-testid="googleAutoComplete"
      {...props}
      onChange={() => {
        props?.selectProps?.onChange({ value: { place_id: 'PLACE_ID' }, label: 'ADDRESS' });
      }}
    />
  ),
}));

**Comment by AshishGz** [comment]
I mocked in the following way: 
`mock the component and use as follow :
jest.mock('react-google-places-autocomplete', () => ({
__esModule: true,
geocodeByPlaceId: jest.fn(
() =>
new Promise((resolve) => {
resolve([
{
address_components: [
{
long_name: 'long_name',
short_name: 'short_name',
types: ['administrative_area_level_1'],
},
{
long_name: 'long_name',
short_name: 'short_name',
types: ['locality', 'political'],
},
{
long_name: 'long_name',
short_name: 'short_name',
types: ['country', 'political'],
},
],
},
]);
}),
),
getLatLng: jest.fn().mockRejectedValueOnce(new Error('Error')).mockResolvedValue({ lat: 0, lng: 0 }),

// eslint-disable-next-line react/display-name
default: (
props: React.DetailedHTMLProps<React.InputHTMLAttributes, HTMLInputElement> & {
selectProps: { onChange: (value: GoogleAutoCompleteValues) => void };
},
) => (
<input
data-testid="googleAutoComplete"
{...props}
onChange={() => {
props?.selectProps?.onChange({ value: { place_id: 'PLACE_ID' }, label: 'ADDRESS' });
}}
/>
),
}));`

**Comment by rimpu** [comment]
I also later researched and did in a similar fashion.

`jest.mock('react-google-places-autocomplete', () => {
  const originalModule = jest.requireActual('react-google-places-autocomplete');
  return {
    __esModule: true, // Use it when dealing with esModules
    ...originalModule,
    geocodeByPlaceId: () => new Promise((resolve) => resolve(mockData)),
  };
});`
