### ISSUE TITLE
Add ability to query place details on select

### ISSUE THREAD

**Issue by ataravati** [Tintef/react-google-places-autocomplete#270]
We need to get the place photos when the item is selected. It would be nice to add ability to query the place details.

**Comment by ataravati** [comment]
@Tintef That's not true.

https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteSessionToken


react-native-google-places-autocomplete uses the same API, of course, but it gives you the place details too.

**Comment by Tintef** [comment]
@ataravati Isn't it using the [Places Service](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails)?

Check [this part](https://github.com/fullstackProDev/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L301-L309) of their code.

I'm not saying it's not doable, I'm saying it's not supported by the google library currently being used on this project.

I do agree that it would be a nice addition to this, so I created [this ticket](https://github.com/Tintef/react-google-places-autocomplete/projects/2#card-83279600) for it.

**Comment by ataravati** [comment]
It shouldn't be difficult to implement. Thanks for creating the ticket!
