### ISSUE TITLE
Needs updating to React Version 18

### ISSUE THREAD

**Issue by mike-niemand** [Tintef/react-google-places-autocomplete#271]
Hi,

This needs to be updated to react@^18

```
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-google-places-autocomplete@3.3.4
npm ERR! node_modules/react-google-places-autocomplete
npm ERR!   react-google-places-autocomplete@"*" from the root project
```

**Comment by Tintef** [comment]
Will try to get to this over this weekend (also, a PR is welcomed...)

**Comment by farrukhrashid1997** [comment]
Hi tintef, can I pick this up?

**Comment by Tintef** [comment]
@farrukhrashid1997 Yeah, feel free to open a PR

**Comment by AndrewBordin** [comment]
Hey guys, any update on this?

**Comment by Tintef** [comment]
I haven't have free time to work on this. A PR is appreciated.

**Comment by farrukhrashid1997** [comment]
I will be getting some time after 6th of July, will try to open a PR asap then.

**Comment by epalacio90** [comment]
I just added a pull request that solves this issue [https://github.com/Tintef/react-google-places-autocomplete/pull/276](url)

**Comment by Tintef** [comment]
Deployed on 3.4.0 :)
