### ISSUE TITLE
Error Message in Next JS - TypeError: (0 , o.rulesheet) is not a function

### ISSUE THREAD

**Issue by ticpoi** [Tintef/react-google-places-autocomplete#277]
When we used the library on local everything was fine. But on deployment it broke the complete application and throwed "TypeError: (0 , o.rulesheet) is not a function" error message seen on console.

On first research it looks like related with import statements.
So tried these;
import GooglePlacesAutocomplete from 'react-google-places-autocomplete'
import { getLatLng, geocodeByAddress } from 'react-google-places-autocomplete'

or

import GooglePlacesAutocomplete , { getLatLng, geocodeByAddress } from 'react-google-places-autocomplete'

None of them worked on server.

So I removed the library and the problem gone.

**Comment by thallada** [comment]
I am seeing a similar error using Next.js but only in development mode:

![Screen Shot 2022-10-03 at 2 18 30 PM](https://user-images.githubusercontent.com/1505923/193649798-dd5ec984-ab57-4821-a1a8-ea308611a4f5.png)
![Screen Shot 2022-10-03 at 2 18 42 PM](https://user-images.githubusercontent.com/1505923/193649801-f6b7f845-f95f-42c4-858d-6fcba45bf6ce.png)

**Comment by madaher-dev** [comment]
I think this is related that nextJs updates to React 18 and the version of react-select used in the library is the older version. There is an open issue since november and still no bump to the existing dependency :(

**Comment by Tintef** [comment]
@ticpoi This should be fixed now on v4.0.0. Will close the issue but if it's still preset lmk and I can reopen!

Bare in mind I had to use a dynamic import.
