### ISSUE TITLE
How to customize `No options` label

### ISSUE THREAD

**Issue by alimoli** [Tintef/react-google-places-autocomplete#278]
I checked the documentation, code, and several examples, but I cannot find a way to customize `No options` label.
Is there some property?

**Comment by matheusmirandaferreira** [comment]
I would like to know too

**Comment by Tintef** [comment]
Sounds like you want to search on [react-select docs](https://react-select.com/props) and use the `selectProps`prop of this component.

You want to use the `noOptionsMessage` prop or a custom component, check their docs.

**Comment by coucoseth** [comment]
For those who do not want to read the lengthy documentation of react-select, inside `selectProps`
```
noOptionsMessage: () => "input your custom message here",
```
