### ISSUE TITLE
onChange not working 3.4.0

### ISSUE THREAD

**Issue by eldan88** [Tintef/react-google-places-autocomplete#279]
Hi, 

 Below is the code i am using and the onChange event is not working.. 
```
<GooglePlacesAutocomplete   selectProps={{
                                        onChange: (res)=> {console.log(res)},
                                        placeholder: 'Enter Steet Address',
                                        className : "form-control border-0 shadow-0",
                                        components : {
                                        IndicatorSeparator: () => null,
                                            DropdownIndicator: () => null
                                    },
                                        styles : {
                                            control: base => ({
                                                ...base,
                                                border: 0,
                                                // This line disable the blue border
                                                boxShadow: 'none'
                                            })},

                                    }}

/>
```

**Comment by Tintef** [comment]
@eldan88 works fine for me. Is the google places script loaded?

**Comment by eldan88** [comment]
No i didn't you put in your documentation 

Note: if you pass down the apiKey prop to the component, you can skip loading the [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/), as the component will inject that script on the page.

**Comment by Tintef** [comment]
I cannot reproduce your issue, so there's not much I can do. If you want to share with me a repo or sth where the issue can be reproduced, I can take another look.

**Comment by eldan88** [comment]
Hey. 

 I am using nextjs to implement this... it doesnt seem to output the log.. but on code sandbox its working fine...

**Comment by eldan88** [comment]
Hey okay so for some reason dont know why it doesnt output it on the console log. Not for nexjs and not for a react app i have. Not sure why. 

But it does work when i use alert()

Not sure why..
