### ISSUE TITLE
Is there a changelog currently?

### ISSUE THREAD

**Issue by YPCrumble** [Tintef/react-google-places-autocomplete#286]
Thank you for maintaining this package! This dropped in really nicely without any hassles and exposing the react-select API provides amazing functionality.

I'm wondering if there is a changelog? I couldn't see one in the docs, GitHub, or the NPM registry but wanted to make sure I wasn't missing it.

**Comment by Tintef** [comment]
Thank you for the kind words 😄 Glad to hear you're liking the package!

Regarding the changelog, no, there's not one 😞 

You needed one for something in particular?

**Comment by YPCrumble** [comment]
Got it thank you! Just to know what changed between versions and determine whether and when I want to upgrade.

**Comment by Tintef** [comment]
Sounds like something I could start doing, as it's easy enough. For now, the only thing that kinda tells what changes is the [migration guide from v2 to v3](https://tintef.github.io/react-google-places-autocomplete/docs/v2-to-v3/).

Then, everything v3.x release are small enhancements or security patches IIRC
