### ISSUE TITLE
Cannot read properties of null (reading 'removeEventListener')

### ISSUE THREAD

**Issue by harunbiswas** [Tintef/react-google-places-autocomplete#291]
hi, 
When I click or onFocus on the input box I found the issue 
please see the attachment
![Screenshot from 2022-09-16 15-36-13](https://user-images.githubusercontent.com/77938106/190607866-de36af8b-e593-4440-a557-90b4f401a0d1.png)
!

**Comment by Tintef** [comment]
How are you using the component? [This issue seems related](https://github.com/JedWatson/react-select/pull/4213).

**Comment by Tintef** [comment]
Closing due to lack of response.
