### ISSUE TITLE
Types parameter not being sent in autocomplete request

### ISSUE THREAD

**Issue by koraybilgi** [Tintef/react-google-places-autocomplete#293]
The package is sending autocomplete requests without the **types** parameter set in the options.

For example, let's say I just want to get a list of hospitals.

```javascript
<GooglePlacesAutocomplete
	minLengthAutocomplete={3}
	debounce={500}
	selectProps={{
		id: 'google-places-id',
		instanceId: 'google-places-id',
		autocompletionRequest: {
			types: ["hospital"]
		} 
	}}
/>
```
The sample code generates the following request:
`https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictionsJson?1scem&15e3&21m1&2e1&callback=_xdc_._l28uvb&key=XXX&token=XXX`

But instead it should have created the request like this:
`https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictionsJson?1scem&15e3&21m1&2e1&callback=_xdc_._l28uvb&key=XXX&token=XXX`**&9shospital**

Browser:
`Chrome Version 105.0.5195.125 (Official Build) (x86_64)`

package.json: 
```json
{
  "name": "XXX",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build && next export",
    "start": "next start"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.8.5",
    "aos": "^2.3.4",
    "axios": "^0.27.2",
    "bootstrap": "^5.2.0",
    "cookies-next": "^2.1.1",
    "lodash": "4.17.21",
    "next": "^12.3.1",
    "node-sass": "^7.0.1",
    "react": "18.2.0",
    "react-bootstrap": "^2.5.0",
    "react-countup": "^6.3.1",
    "react-device-detect": "^2.2.2",
    "react-dom": "18.2.0",
    "react-google-places-autocomplete": "^3.4.0",
    "react-icons": "^4.4.0",
    "react-redux": "^8.0.2",
    "react-select": "^5.4.0",
    "react-simple-star-rating": "^4.0.5",
    "react-toastify": "^9.0.8",
    "sass": "^1.54.8"
  },
  "devDependencies": {
    "eslint": "8.23.0",
    "eslint-config-next": "12.2.5"
  }
}

```

**Comment by Tintef** [comment]
@koraybilgi `autocompletionRequest` shouldn't be inside `selectProps`, can you try with

```
<GooglePlacesAutocomplete
	minLengthAutocomplete={3}
	debounce={500}
	autocompletionRequest={{
		types: ["hospital"]
	}}
	selectProps={{
		id: 'google-places-id',
		instanceId: 'google-places-id',
	}}
/>
```

**Comment by Tintef** [comment]
Closing due to lack of response (+ wrong usage of the prop, if the suggestion doesn't work I'll reopen).
