### ISSUE TITLE
IsDisabled field in selectprops disables the field but also hides the data

### ISSUE THREAD

**Issue by anagharajan95** [Tintef/react-google-places-autocomplete#309]
I am trying to use isDisabled props for <> component where I need the select box to be disabled/readonly but if any value is already selected that need to be rendered in the selectbox wih disabled style...But currently the box is disabled but the value also gets hidden.
![image](https://user-images.githubusercontent.com/102807287/203512143-353dd248-d5a7-4b7c-92ae-0691ceacda29.png)

But when i inspect the component the value is seen in the inspect element section
![image](https://user-images.githubusercontent.com/102807287/203513251-a6f45f91-a22e-44dd-bbc9-97136e1a5d39.png)
Can anyone please help to understand why this issue happens

**Comment by Tintef** [comment]
What's `locationData` there? `selectProps` are props for the underlying `react-select` component as explained [here](https://tintef.github.io/react-google-places-autocomplete/docs/props#selectprops).

As you are passing down an `onChange` it looks like you want to use it as a controlled input, please [read the docs about how to do it](https://tintef.github.io/react-google-places-autocomplete/docs/examples).
