### ISSUE TITLE
Weak Documentation 

### ISSUE THREAD

**Issue by mhr996** [Tintef/react-google-places-autocomplete#310]
Where do I find examples or demos of this? The documentation is very weak and unclear!
How do I handle the selected address? 
I followed all the steps in the doc but the suggestions aren't even showing up! 
Please provide an example of how this is fully used.

**Comment by Tintef** [comment]
I think the [examples page](https://tintef.github.io/react-google-places-autocomplete/docs/examples/) have the basics for everyone to get started.

What have you tried?

**Comment by zacker101** [comment]
@Tintef I used the same example as yours in the examples page, but whatever i search doesn't show up or do anything, the value state is not being updated it stays null and there are no errors showing, i checked my API, and it's receiving requests, but nothing is happening from my end

**Comment by Tintef** [comment]
@zacker101 Can you share some code?

**Comment by Christonit** [comment]
I'm facing the same issues: onClick on the options no value is being set, but using the arrows and pressing enter do set the a new value.
**
![image](https://user-images.githubusercontent.com/9038827/206865277-d2e60726-af27-4ab9-81e6-b9889cfd8315.png)
**

**Comment by Tintef** [comment]
Why are you trying to use `onClick` there? AFAIK is not a [react-select select props](https://react-select.com/props#select-props).

**Comment by Tintef** [comment]
Closing due to lack of response.
