### ISSUE TITLE
Form control input value going out of view

### ISSUE THREAD

**Issue by aliyaus** [Tintef/react-google-places-autocomplete#319]
Seeing a possible intermittent issue where typing anything moves the text to the left of the autocomplete container and you can only see the last few characters of what you entered. Seeing this on a Safari browser. 

Can anyone assist please? 

<img width="613" alt="Screenshot 2023-03-12 at 11 25 05 PM" src="https://user-images.githubusercontent.com/65532838/224608627-d48e2df5-1919-4493-9df6-6bc1a7f4a64d.png">

**Comment by aliyaus** [comment]
<img width="613" alt="Screenshot 2023-03-12 at 11 25 05 PM" src="https://user-images.githubusercontent.com/65532838/224608603-8c20b0ec-45dd-4900-b9d3-cb2e38dd0c3e.png">

**Comment by Tintef** [comment]
Please provide code to reproduce

**Comment by aliyaus** [comment]
App.js
```
<div className="main-section">
<h1>Header Title</h1>
<div className="autocomplete-container">
       <GooglePlacesAutocomplete
                        apiKey={API_KEY}
                        selectProps={{
                            value: searchObj.value,
                            onChange: (value) => onChangeAddress(value),
                            placeholder:  "search"
                        }}
                    />
</div>
</div>
```

css
```
.main-section-content {
  padding: 10vh 5vw;
}

.autocomplete-container {
  margin-bottom: 2vh;
}
```

**Comment by Tintef** [comment]
That's not enough to exactly reproduce your issue, but using similar code it works just fine on codesandbox, so I'm guessing it has something to do with either your `searchObj` or what you are doing on `onChangeAddress`.

```
import { useState} from 'react';
import GooglePlacesAutocomplete from 'react-google-places-autocomplete';
import "./styles.css";

export default function App() {
  const [value, setValue] = useState('');

  return (
    <div className="main-section">
      <h1>Header Title</h1>
      <div className="autocomplete-container">
        <form>
          <GooglePlacesAutocomplete
            apiKey={API_KEY}
            selectProps={{
              value,
              onChange: (value) => setValue(value),
              placeholder:  "search"
            }}
          />

          <button className="submit-ban" onSubmit={console.log}>
            Search
          </button>
        </form>
      </div>
    </div>
  );
}
```
