### ISSUE TITLE
react 16 deprecation warning

### ISSUE THREAD

**Issue by steven-r** [Tintef/react-google-places-autocomplete#32]
While using GootPlacesAutocomplete with react 16.9, I get the following warning: 
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: GooglePlacesAutocomplete
```

Versions:

* react: 16.9
* react-google-places-autocomplete: 1.5.3

**Comment by Tintef** [comment]
Hi @steven-r, I'm aware of this and I've got an item pipeline to update the library to follow the newest stuff on React (such as using hooks or update the lifecycle methods being used on the library).

Sadly, I don't have enough time right now to do so, but thanks for pointing it out!

Feel free to submit a PR to update the lifecycle hook being used if you want to!!
