### ISSUE TITLE
City Filtering

### ISSUE THREAD

**Issue by 1sahinomer1** [Tintef/react-google-places-autocomplete#321]
Hi,

I want only suggestions for a city in a country.
I did a lot of research, I also tried locations such as bounds, but I couldn't get much result.

For example, I want to display only the results for Istanbul for Turkey.

I would be very grateful if anyone can help with this. Thanks for your help.

**Comment by bytemtek** [comment]
Hello,

I add this apiOptions={{ language: 'fr', region: 'fr' }} but still I can see another country results.

**Comment by ashish13377** [comment]
use like this it will work for you :

<GooglePlacesAutocomplete
        className="nosubmit"
         apiKey="YOUR_API_KEY"
         apiOptions={{ region: 'IN' }}
         selectProps={{
                   styles: {
                        input: (provided) => ({
                               ...provided,
                                color: 'black',
                        }),

                        option: (provided, state) => ({
                                ..provided,
                                backgroundColor: state.isFocused ? '#93294B' : 'transparent', // Change background color on hover
                                color: state.isFocused ? 'white' : 'black'
                         }),
                         singleValue: (provided) => ({
                              ...provided,
                              color: 'black',
                         }),
                   },
                  value,
                  onChange: setValue,
                  placeholder: 'Enter a location...',
}} / >.

**Comment by emad-ir** [comment]
If you want addresses to be shown only for a certain country, the way to do it is with the prop `autocompletionRequest`

`<GooglePlacesAutocomplete
                apiKey={API_KEY}
                autocompletionRequest={{
                    componentRestrictions: {
                        country: "ZA",
                    },
                }}
                selectProps={{...otherProps}}
            />`
