### ISSUE TITLE
Autocomplete options are behind other sections

### ISSUE THREAD

**Issue by yvan99** [Tintef/react-google-places-autocomplete#325]
can you help me please with this issue?

![WhatsApp Image 2023-06-02 at 17 06 18](https://github.com/Tintef/react-google-places-autocomplete/assets/23630154/e695fb03-8127-4f40-930c-9e48a24f7832)

here's my component

` <GooglePlacesAutocomplete
                      apiKey={MAPS_API_KEY}
                      autocompletionRequest={{
                        componentRestrictions: {
                          country: [countryCode],
                        },
                      }}
                      selectProps={{
                        styles: {
                          input: (provided) => ({
                            ...provided,
                            minWidth: 'max-content'
                          }),
                        },
                        required: true,
                        placeholder: address
                          ? address
                          : 'Enter Your Delivery Address',
                        onChange: (e) => handlePlaceAddressChange(e),
                      }}
                    />`

**Comment by Tintef** [comment]
@yvan99 Please provide a repo to reproduce.

**Comment by yvan99** [comment]
> @yvan99 Please provide a repo to reproduce.

Thanks, @Tintef  , unfortunately, it is a company's private repo, making it challenging to share. was wondering if there is any specific prop needed there because I also had the same issue with a `select` component of `react-select` and had to add this to work. 
<img width="469" alt="Screenshot 2023-06-09 114124" src="https://github.com/Tintef/react-google-places-autocomplete/assets/23630154/9651dbe9-9fb4-4db4-b222-2b4baab8ac1b">

**Comment by Tintef** [comment]
You can target the inner react select and do that as well, check [this docs](https://tintef.github.io/react-google-places-autocomplete/docs/examples)
