### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by bytemtek** [Tintef/react-google-places-autocomplete#326]
Hello,

How can I remove blue border around Test text.

Thank you.

<img width="880" alt="Screenshot 2023-06-05 at 21 30 27" src="https://github.com/Tintef/react-google-places-autocomplete/assets/8950642/49cc4795-781d-4961-ab4f-0e60bb9222c8">

**Comment by Tintef** [comment]
I think you want the [Customization section of the docs](https://tintef.github.io/react-google-places-autocomplete/docs/examples)
