### ISSUE TITLE
Warning for multiples

### ISSUE THREAD

**Issue by Shrewbi** [Tintef/react-google-places-autocomplete#33]
I've attempted to have two of these autocomplete components and it works, however i am warned since it utilizes the same id twice: 

> [DOM] Found 2 elements with non-unique id #google-places-autocomplete-input: (More info: https://goo.gl/9p2vKq)

**Comment by Tintef** [comment]
@Shrewbi Thanks for pointing this out!

If you use custom render functions, you can override the `id` of the input, the suggestions container, and each suggestion item. But, I do agree that having to this if you are ok with the default input/suggestions is not great.

I think that a good approach could be to pass an `idPrefix` prop 🤔 

PR and more thoughts on this are welcomed!
