### ISSUE TITLE
Getting warning regarding "Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading

### ISSUE THREAD

**Issue by sadanandapradhan** [Tintef/react-google-places-autocomplete#344]
Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading.. Getting the same warning again and again ... After changed at Script level also  .. Here is my Script tag   <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"> and also tried "<script async defer loading="async"
src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places&callback=showNewLocationFunc">
</script>
"
</script>   .. So any one please guide me

**Comment by lightstrike** [comment]
@sadanandapradhan Add the `async` script attribute and `loading=async` into the `src` value as noted [in the docs](https://developers.google.com/maps/documentation/javascript/place-autocomplete):
```html
<script async
    src="https://maps.googleapis.com/maps/api/js?key=&loading=async&libraries=places&callback=initMap">
</script>
```

**Comment by sadanandapradhan** [comment]
Thank You @lightstrike  its working properly

**Comment by splintor** [comment]
@lightstrike  If I don't have a `<script>` tag to load, and instead I pass the `apiKey` as a prop to the component, is there a way to avoid this warning? Can I tell the component to add the script with `loading=async`?

**Comment by splintor** [comment]
It seems this was added to `@googlemaps/js-api-loader` in version **1.16.3** (in this PR), so all we need to do is update to the latest version.

**Comment by lightstrike** [comment]
Good sleuthing @splintor, that should fix it 👍 

We ended up migrating to the [Places Autocomplete Service](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service).  I haven't tested this `react-google-autocomplete` library though at a glance it looks like a close parallel to our implementation: https://github.com/ErrorPro/react-google-autocomplete?tab=readme-ov-file#useplacesautocompleteservice

Worth checking as it doesn't appear this package is actively maintained currently.
