### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 () in reactjs

### ISSUE THREAD

**Issue by arsalan06** [Tintef/react-google-places-autocomplete#349]
![Capture6](https://github.com/Tintef/react-google-places-autocomplete/assets/117338478/abf808cb-ecad-4c1d-9e44-866ca9c1cee8)

when I run my project the browser shows a blank screen. it works only when I delete browser cache

**Comment by Tintef** [comment]
Is this related to this project? Doesn't seem to be on the dependency list. Closing for now.
