### ISSUE TITLE
Warning about 'defaultProps'

### ISSUE THREAD

**Issue by alexbmt84** [Tintef/react-google-places-autocomplete#350]
### Description
Hello, I've noticed that using `GooglePlacesAutocomplete` generates a React warning regarding the upcoming deprecation of `defaultProps` in function components. The warning suggests that this might lead to future compatibility issues with React.

### Details
- React Version: [e.g., 17.0.2]
- Library Version: [e.g., 1.2.3]
- Warning Message: [copy and paste the exact warning message]

### Request
Could you please let us know if there are any plans to update the library to address this deprecation? Alternatively, could you suggest any workarounds?

Thank you for maintaining this useful library!

**Comment by gergokee** [comment]
fix is here, just need to be merged:
https://github.com/Tintef/react-google-places-autocomplete/pull/341

**Comment by Tintef** [comment]
Merged that PR. Will test and hopefully deploy a new version tomorrow.

**Comment by Tintef** [comment]
Hey, this has been now deployed on 4.1.0.
cc: @gergokee @alexbmt84
