### ISSUE TITLE
clear input

### ISSUE THREAD

**Issue by theweiweiway** [Tintef/react-google-places-autocomplete#38]
Hi, 

Thanks for the great library.

i was wondering if there is a way to programmatically clear the input field? I'm using renderInput to apply my styling, and I read that onChange should not be overriden. 

Thanks again.

**Comment by Tintef** [comment]
Hi @theweiweiway,

Currently there's no way to programmatically clear the input field, but that sounds like a great addition!
Any PR or suggestions are more than welcome, but I'll try to take a look at this ASAP.

Also, can you provide some sample code of how you intend to do it? And the use case?

Thanks!

**Comment by theweiweiway** [comment]
Thanks for the response @Tintef,

I have successfully implemented the component to work. Now, i want to build in the capability to click a X icon which will programatically clear the input. My code is below (I'm using @materialui/core for styling), and the part where the input will be cleared is commented out.

Thanks!

Here's my code:
```
<GooglePlacesAutocomplete
          {...props}
          onSelect={async (result: any) => {
            const locations = await geocodeByPlaceId(result.place_id)
            const locationDetails = locations[0]
            const latLng = await getLatLng(locationDetails)
            const locationData = {
              longLat: [latLng.lng, latLng.lat],
              location: locationDetails,
            }
            props.onSelect(locationData)
          }}
          loader={<LinearProgress />}
          renderInput={(props: any) => {
            return (
              <TextField
                {...props}
                placeholder="Enter your city or address"
                variant="outlined"
                fullWidth
                InputProps={{
                  classes: {
                    input: classes.textField,
                  },
                  endAdornment: (
                    <InputAdornment position="end">
                      <div style={{ display: "flex" }}>
                        {/* <CloseIcon
                        onClick={() => { PROGRAMATICALLY CLEAR THE INPUT ON CLICK }}
                        style={{
                          cursor: "pointer",
                          fontSize: 20,
                          marginRight: 8,
                          color: "grey",
                        }}
                      /> */}
                        <MyLocationIcon style={{ fontSize: 20 }} />
                      </div>
                    </InputAdornment>
                  ),
                }}
              />
            )
          }}
          renderSuggestions={(
            active: any,
            suggestions: any,
            onSelectSuggestion: any
          ) => {
            return (
              <Paper className={classes.suggestionWrapper} elevation={8}>
                {suggestions.map((suggestion: any, idx: number) => (
                  <div
                    key={idx}
                    className={classes.suggestion}
                    onClick={event => onSelectSuggestion(suggestion, event)}
                  >
                    <LocationIcon
                      style={{
                        fontSize: 20,
                        margin: 0,
                        padding: 0,
                        marginRight: 5,
                      }}
                    />
                    {suggestion.description}
                  </div>
                ))}
              </Paper>
            )
          }}
          debounce={200}
        />
```

**Comment by theweiweiway** [comment]
@Tintef I cloned the repo and took a look, 
What do you think of exposing ``value`` as a **mandatory** prop (like this: https://github.com/hibiken/react-places-autocomplete)? 
That way the user can do whatever they want with the value, however it would require a mandatory value prop which the user would need to keep track and manage.

**Comment by theweiweiway** [comment]
The other option i see is to use a ref to trigger ``changeValue(value)`` from the parent

**Comment by theweiweiway** [comment]
sorry. this is actually much easier than i thought haha...

since in the state declaration, you did ``value: props.initialValue``, I can just do this:
```
const [input, setInput] = useState('initial value')

<GooglePlacesAutocomplete
  initialValue={input}
/>
<Button onClick={() => setInput('')}>
  set new input value
</Button>
```

and that will clear the input... 

Great!

**Comment by elicleveland12** [comment]
I am attempting to use a single <GooglePlacesAutocomplete/> component to get multiple locations (which will be used as routing waypoints) and I would like to be able to clear the input field every time onSelect hits. I tried @theweiweiway solution and it only seems to work the first time setInput('') fires. I tried two different ways: adding setInput('') to the onSelect function and adding a button to fire setInput('') onClick. Any suggestions?

Thank you

**Comment by theweiweiway** [comment]
My workaround:
`
const LocationSearch = ({ children }: any) => {
  const { searchState, searchDispatch } = useContext(SearchContext);
  const [value, setValue] = useState(
    searchState.address ? searchState.address : ""
  );
  const [showing, setShowing] = useState(true);

  useEffect(() => {
    if (searchState.address) {
      setValue(searchState.address);
    }
  }, [searchState.address]);

// to allow clear button to work and reset to "" string by unmounting and remounting component
  useEffect(() => {
    if (!value) {
      setShowing(false);
    }
  }, [value]);

// to allow clear button to work and reset to "" string by unmounting and remounting component
  useEffect(() => {
    if (!showing) {
      setShowing(true);
    }
  }, [showing]);

return (
    <div className={classes.root}>
      {showing && (
        <GooglePlacesAutocomplete
         ...
        />
      }
     <Button onClick={() => {
        setValue("")
        }}>clear</Button>
    </div>
`

When you click clear, it sets the input address value to an empty string "". This triggers the `showing` variable to be false, which unmounts the GooglePlacesAutocomplete. The lifecycle then triggers the second useEffect, which triggers `showing` to be true again. This clears the input
