### ISSUE TITLE
Unable to force user to select autocomplete.

### ISSUE THREAD

**Issue by Sushant-Borsania** [Tintef/react-google-places-autocomplete#39]
Unable to force user to select from autocomplete suggestion only. Since there is no freedom to modify the onBlur method, I am unable to implement the functionality.

**Comment by Tintef** [comment]
@Sushant-Borsania 

You can override the `onBlur` function. The README needs an update regarding that.
If you take a look at the `renderInput` function: https://github.com/Tintef/react-google-places-autocomplete/blob/master/src/GooglePlacesAutocomplete/index.js#L109-L154, you can see that there's no `onBlur` method being used.

**Comment by Sushant-Borsania** [comment]
Thank you. Yes I override the blur and working as expected...
