### ISSUE TITLE
Get location data from selected autocomplete item

### ISSUE THREAD

**Issue by dstiglr** [Tintef/react-google-places-autocomplete#46]
Hello.

I can't get location data from object given by onSelect method.

**Comment by Tintef** [comment]
Hi @dstiglr, what field are you looking for? Can you send some sample code of what you are doing and what you are trying to accomplish?

If by `location data` you mean that you want to get `lat` and `long`, you can't. You'll need to geocode the location after getting it. You can use the provided `getLatLng` function.

**Comment by dstiglr** [comment]
I get it, thanks.
