### ISSUE TITLE
Ability to specify sessionToken on every suggestion call?

### ISSUE THREAD

**Issue by a-ssassi-n** [Tintef/react-google-places-autocomplete#49]
According to Dev Docs from Google, you must specify a 'sessionToken' for every suggestion call. When an address is selected, the `sessionToken` is expired and you are charged for the suggestion.

- https://developers.google.com/places/web-service/session-tokens

- https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/places-autocomplete#session_tokens

Is there any way to create a token like so:

`const sessionToken = new.google.maps.places.AutocompleteSessionToken();`

and pass it to some props of  `<GooglePlacesAutocomplete>` ?

**Comment by Tintef** [comment]
Hi @a-ssassi-n, currently there's no way to do that. But it does seem very important.

I'll try to add that as soon as possible, but a PR is always welcomed! 😄

**Comment by Tintef** [comment]
@a-ssassi-n you can try this out by installing the `2.0.0-alpha.2` version.
You can pass a `withSessionToken` prop and it will handle changing the `sessionToken` after every place select for you.

**Comment by Tintef** [comment]
Feature added on #52

**Comment by Tintef** [comment]
Feature added on #52
