### ISSUE TITLE
Failed prop type: Invalid prop `bounds` supplied to `GooglePlacesAutocomplete`

### ISSUE THREAD

**Issue by fridaystreet** [Tintef/react-google-places-autocomplete#5]
Getting the error Failed prop type: Invalid prop `bounds` supplied to `GooglePlacesAutocomplete`

Regardless of if I supply the autocompletionRequest prop to the component. If I do supply property without bounds, same issue. If i supply with bounds: {} same issue.

Cheers
Paul

**Comment by Tintef** [comment]
@fridaystreet Can you provide some example code please?

**Comment by Tintef** [comment]
@fridaystreet Don't worry, I was able to reproduce it

**Comment by fridaystreet** [comment]
Awesome thanks. Sorry I'm in Australia so only just seen this message.

**Comment by Tintef** [comment]
No problem! Thank you for reporting this 😄
