### ISSUE TITLE
Get Map Url

### ISSUE THREAD

**Issue by faizaaniesta** [Tintef/react-google-places-autocomplete#54]
I want to achieve the following effect with your library:
`
const autocomplete = new google.maps.places.Autocomplete(
      document.getElementById('autocomplete'),
      options,
);

const mapUrl = autocomplete.getPlace().url;
`
How can I get the google maps url?

**Comment by Tintef** [comment]
@faizaaniesta I don't think you can exactly that, but you can construct a google maps url if you have the `lat` and `lng` values for the place.

```
import GooglePlacesAutocomplete, { getLatLng, geocodeByPlaceId } from 'react-google-places-autocomplete';

<GooglePlacesAutocomplete
  apiKey="<YOUR_API_KEY>"
  onSelect={({ place_id: placeId }) => {
    geocodeByPlaceId(placeId).then(res => {
      getLatLng(res[0]).then(({ lat, lng }) => {
        console.log(`https://www.google.co.in/maps/@${lat},${lng},9z`);
      });
    });
  }}
/>
```

This will log in the console a url to google maps centered in the place the user selected on the autocompleted.

Hope it helps!

**Comment by faizaaniesta** [comment]
You are right but what if I wanted the map to point at some object, for example, https://maps.google.com/?q=1275+York+Ave,+New+York,+NY+10065,+USA&ftid=0x89c258c24d923e7f:0xfbb658dfc641e314

When I visit this url, the map directly points at the place, whereas, if I just add its `lng `,`lat `to your given url it won't be pointed out in the map.

**Comment by Tintef** [comment]
@faizaaniesta If you wanna do that, by looking at the url you just need to pass the description that google places API returns, like this:
```
<GooglePlacesAutocomplete
  apiKey="< YOUR_API_KEY >"
  onSelect={({ description }) => {
    console.log(encodeURI()`https://www.google.com/maps/place/${description}`))
  }}
/>
```

Hope this helps!

**Comment by faizerestek** [comment]
Awesome! Thanks.

**Comment by Tintef** [comment]
Will close this assuming last answer is what @faizaaniesta wanted
