### ISSUE TITLE
Properly way to use onSelect with typescript

### ISSUE THREAD

**Issue by gabe2code** [Tintef/react-google-places-autocomplete#61]
Hi everyone:
I need to know whats the right way to use `onSelect` with Typescript cause I'm receiving a warning when I use it. This is my code: 

`handleSelect = (addressSelected:any):void => {`
`    geocodeByPlaceId(addressSelected.place_id)`
`      .then(results => results[0])`
`      .then(latLng => console.log('Success', latLng))`
`      .catch(error => console.error('Error', error));`
`  };`

`  componentDidCatch(error: Error, errorInfo: React.ErrorInfo): void {`
`    console.log(`error: ${error}, errorInfo: ${errorInfo}`);`
`  }`

`  searchOptions = {`
`    componentRestrictions: { country: 'us' },`
`  };`

`  render(): React.ReactElement {`
`    return (`
`      <GooglePlacesAutocomplete`
`        autocompletionRequest={this.searchOptions}`
`        onSelect={this.handleSelect}`
`        initialValue={this.props.initialValue}`
`      />`
   ` );`
 ` }`

This is the warning I'm receiving :

`The expected type comes from property 'onSelect' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<GooglePlacesAutocomplete> & Readonly<GooglePlacesAutocompleteProps> & Readonly<...>`

Thanks beforehand 👍

**Comment by Tintef** [comment]
@gabe2code I'm not a Typescript user myself, but I'll check this as soon as I get a change.

**Comment by Tintef** [comment]
@gabe2code Noticed it's a bug on the typescript definition for the props. Working on a fix now

**Comment by Tintef** [comment]
@gabe2code Thanks for catching and reporting this!

In the new release (2.0.4) you can use it like this:

```
import React from 'react';
import GooglePlacesAutocomplete, { geocodeByPlaceId } from 'react-google-places-autocomplete';
import 'react-google-places-autocomplete/dist/index.min.css';

class App extends React.Component<any, {}> {
  onSelect = (selection: any):void => {
    geocodeByPlaceId(selection.place_id)
      .then(results => results[0])
      .then(latLng => console.log('Success', latLng))
      .catch(error => console.error('Error', error));
  };

  renderInput = (props: any):JSX.Element => <input {...props} />

  renderSuggestions = (active: number, suggestions: Array<any>, onSelect: (suggestion: any, event: any) => void):JSX.Element => (
    <div>
      {
        suggestions.map(sugg => (
          <div
            key={sugg.id}
            className="suggestion"
            onClick={(event) => onSelect(sugg, event)}
          >
            {sugg.description}
          </div>
        ))
      }
    </div>
  )

  render(): React.ReactElement {
    return (
      <div className="App">
        <GooglePlacesAutocomplete
          apiKey="*******"
          onSelect={this.onSelect}
          renderInput={this.renderInput}
          renderSuggestions={this.renderSuggestions}
        />
      </div>
    );
  }
}

export default App;
```

**Comment by gabe2code** [comment]
Hi @Tintef , looks very good, thanks for the help 👍
