### ISSUE TITLE
[react-google-places-autocomplete]: Google script not loaded. Infinite error throwing

### ISSUE THREAD

**Issue by gabe2code** [Tintef/react-google-places-autocomplete#62]
I'm receiving this error in an infinite loop cause sometimes I work offline, there is no way to catch that error and no keep throwing every time I worked offline?
Something like the onError method or something?

**Comment by Tintef** [comment]
Hey @gabe2code, there's no way to make that error go, as that error is thrown as the component checks for the google places script to be loaded (if this script is not loaded, the autocomplete will not work -- be able to fetch data).

I'll think on the best way to add the ability to suppress this error, any idea is more than welcomed!

**Comment by gabe2code** [comment]
Hey @Tintef, I think the error could solve it doing something like `e.preventDefault` or like a try-catch. If the script is not loaded the autocomplete won't work, that's perfect, you reported to the developer or to the user once and that's it... sounds good? 
Have a great day buddy

**Comment by Tintef** [comment]
@gabe2code I don't fully agree. If you a take a look, the code is polling until the google places script is loaded, so in a slow internet, we could see a couple errors until the script is loaded. Given this, I don't think that just showing one error can do the trick given how the library works now.

In order to just throw one error and be able to call an `onError` callback, the library should be able to "listen" to loading state of the google places script 🤔

**Comment by gabe2code** [comment]
Hey @Tintef, I got your point buddy. What if we try the error in a `componentDidCatch`?. Even in slow networks like mine, the google script not take more than a few seconds to be ready to go... 
Another could be to limit the number of attempts 15 sounds rational and later just stop trying.
I hope that helps 😃

**Comment by Tintef** [comment]
I thought about a max number of attempts, but I don't really like that approach. I'll like to explore if we can know the loading state of the script

**Comment by gabe2code** [comment]
I did a PR to fix this problem, please check it out when you have some time.
👍

**Comment by firestar300** [comment]
Hello, any news on this PR ?

**Comment by gabe2code** [comment]
I've been complicated with a project, I will be uploading the changes
hopefully in this week.

**Comment by Tintef** [comment]
Fixed by #88
