### ISSUE TITLE
"You have included the Google Maps JavaScript API multiple times on this page"

### ISSUE THREAD

**Issue by cwinters8** [Tintef/react-google-places-autocomplete#69]
I'm getting this error in the console when using this component:
`You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`
And sometimes (not all the time - sometimes it works fine but still throws the above warning) when I type in a place name in the rendered component, the dropdown is stuck at "Loading...".

![image](https://user-images.githubusercontent.com/40615752/81761897-d05a4600-9490-11ea-815e-8b487fde11d9.png)

I did have another Google Maps related fetch that I thought was causing the warning but I've removed that to see if it might solve the issue but no dice.

Here's my import
```js
import GooglePlacesAutocomplete from 'react-google-places-autocomplete';
```

And here's a stripped down version of how I'm calling the component
```js
const NewHorse = props => {
  const [location, setLocation] = useState({});
  const [places, setPlaces] = useState([]);

  const setLocationState = data => {
    setLocation({
      id: data.id,
      description: data.description
    });
  }

  const GetLocation = () => {
    if (places.length > 0) {
      // return a select element with places
      console.log(places);
      // return <Select className="horse-form-select horse-form-input places" options={places} defaultValue={places[0]} onChange={onPlacesChange} />
    } else {
      return <GooglePlacesAutocomplete onSelect={setLocationState} apiKey={props.firebaseAPIKey} placeholder="Enter a city or zip code" autocompletionRequest={{types: ["(regions)"]}} />
    }
  }

  return (
    <Form className="horse-form">
      <div className="horse-form-container">
        {/* Location */}
        <Label className="horse-form-label" for="location">Location</Label>
        <div className="location">
          {/* <MdLocationSearching fill="white" className="location-icon" onClick={getLocation} /> */}
          <GetLocation />
        </div>
      </div>
    </Form>
  )
}
```

Any help is greatly appreciated.

**Comment by Tintef** [comment]
Hi @cwinters8,

Can you check the following:
1. Are you sure you are not importing the google maps somewhere else? For example, did you add to you `index.html`? If so, you should remove it from there or don't rely on the library to add the script for you (just remove the `apiKey prop for that).
2. I noticed you are rendering the component only if your places is an empty array, can you try to always return the component? Just to be sure if that can be the issue.

Let me know so we can work through this.
Thanks!

**Comment by cwinters8** [comment]
Hey @Tintef,

I don't have the Google Maps JS API being imported in index.html or elsewhere. I tried pulling the component out and returning it directly in the main NewHorse function component and that seems to have resolved the bug. I'm not sure exactly why that was the problem but it seems to have been. I'll work on finding a workaround for the conditional render. Thanks very much for your response and help!

**Comment by Tintef** [comment]
My guess is that conditionally rendering causes the component to inject the script multiple times 🤔

What version of the library you have installed?

**Comment by cwinters8** [comment]
2.0.5

**Comment by Tintef** [comment]
Thanks! I'll take a look at it over the weekend. Glad you have a workaround until then 🙂

**Comment by cwinters8** [comment]
Cool! Also, thanks very much for the great library. It's super handy and has already saved me a lot of headaches.

**Comment by Tintef** [comment]
@cwinters8 Thanks again for reporting this!

A new fixed version `2.0.6` is already published 😄

**Comment by NikolasJody** [comment]
i have the same problem with this

**Comment by Tintef** [comment]
@NikolasJody what version of the library you have installed?

**Comment by sunviwo** [comment]
@Tintef, I'm getting this same error with version 3.3.2, but I'm using the package in conjunction with @react-google-maps/api@2.7.0 that let me display the selected place on a map. Any workaround please? Thanks in advance.

**Comment by Tintef** [comment]
@sunviwo if you don't pass the `apiKey` prop this library won't try to include the google places script.
