### ISSUE TITLE
suggestionsClassNames not being applied

### ISSUE THREAD

**Issue by cbaron3** [Tintef/react-google-places-autocomplete#72]
I am trying to change the cursor and opacity when a user is hovering over/clicking on a suggestion. To do so, I want to pass in a custom class name using suggestionsClassNames.

Right now I have: 

`<GooglePlacesAutocomplete
    suggestionsClassNames={{ container: '', suggestion: '', suggestionActive: "custom-suggestions-classname--active" }}
`

With this in my main.css

`.custom-suggestions-classname--active {
  color:red;
  opacity: 0.5;
  cursor: 'pointer';
}`

`.custom-suggestions-classname--active:hover {
  color:red;
  opacity: 0.5;
  cursor: 'pointer';
}`

And nothing happens when I click/hover over a suggestion. 

Since the documentation does not provide any examples for suggestionsClassNames, can anyone tell me what I am doing wrong here? I am somewhat new to JS/CSS.

**Comment by cbaron3** [comment]
Solved by

`{{ container: '', suggestion: "custom-suggestions-classname--active" suggestionActive: "custom-suggestions-classname--active" }}`

**Comment by Gopisuresh-Akula** [comment]
Hey @cbaron3 i tired based on your example for me not working could please figure out(react-google-places-autocomplete": "^3.2.1)

<GooglePlacesAutocomplete


    suggestionsClassNames={{ container: 'custom-suggestions', suggestion: "custom-suggestions-classname--active" ,suggestionActive: "custom-suggestions-classname--active" }}
           selectProps={{
            value: location,
            placeholder:"Where are you going?",
          
    
         
 
      />
