### ISSUE TITLE
suggestion not loading

### ISSUE THREAD

**Issue by NikolasJody** [Tintef/react-google-places-autocomplete#73]
script for google API has been loaded in inde.html, suggestions didn't load, tried to use the APIKey props, still not loaded. weird. no referrer  not allowed error on console. Maybe ive used it wrong?

**Comment by Tintef** [comment]
Hi @NikolasJody, can you provide some sample code on how you are trying to use it? And the installed version?

Thanks!

**Comment by NikolasJody** [comment]
hi @Tintef i seem to have found a problem, it is because i have two components with google api on the same page. for some reason only one of them can work at a time. i have fixed it to a certain degree by using another library for my maps.
