### ISSUE TITLE
i integrated google maps api to show the current location of my marker, whether changed by dragging marker or by autocomplete. i want to make the marker drag to override the value in the autcomplete search box, how can i do this?

### ISSUE THREAD

**Issue by NikolasJody** [Tintef/react-google-places-autocomplete#74]
i have placed placeholder as the current address, when i move the marker, the placeholder's value change accordingly, but if i use the autocomplete box, the value of the search box wont change unless i type in a new input.

**Comment by NikolasJody** [comment]
i found a solution. it seems if you put the initial value as address and the map changes the value of the address, the search box will update accordingly. so initial value is in essence value?

**Comment by Tintef** [comment]
Yeah... That needs a small refactor 😓
