### ISSUE TITLE
Adding suggestion to list

### ISSUE THREAD

**Issue by MeeTeeT** [Tintef/react-google-places-autocomplete#76]
Hi,

How can i add suggestion to List. 
I mean, if there is no google autocomplete suggestion found, i would like input val to be a suggestion in the suggestion container.

Thanks.

**Comment by Tintef** [comment]
Hi @MeeTeeT, for that, you would need to use a custom function to render the suggestions. Here's the docs about how to use it: https://github.com/Tintef/react-google-places-autocomplete#rendersuggestions

You'll need to check if the `suggestions` are empty, and, if they are, render the desired value as an option.

Hope this helps!

**Comment by MeeTeeT** [comment]
Hi, thanks to your reply.
I will updates in few hours with codes (at work for now) 

I already use custom function for suggestion and I managed to add a personal suggestion if there are google suggestions.
But it seems that is there is no google suggestation (ex: input "aaaazzzzjdjjfjf"), the suggestion list doesn't appear even if I customize it by adding input field value in suggestion list.

I will publish some code later to be more explicit... 
And sorry for my poor English...

Thanks

**Comment by Tintef** [comment]
@MeeTeeT Yes, you are right, if there are no suggestions nothing gets renders 😞 , forgot about that.

You can find that here: https://github.com/Tintef/react-google-places-autocomplete/blob/25396a4e7ad205dc92fe213cbb73c03558fe0cf0/src/GooglePlacesAutocomplete/index.js#L283

I'm open to move that line below the if statement that returns the custom suggestions render function, but can't do it until maybe this or the next weekend.

If you open a PR I can review and publish to npm as soon as possible 😄
