### ISSUE TITLE
Language restriction

### ISSUE THREAD

**Issue by sashberd** [Tintef/react-google-places-autocomplete#78]
Hi
I wonder if you can add prop for language restriction so I can use like: 
`https://maps.googleapis.com/maps/api/js?key=${googleApiKey}&libraries=places&language=${language}`

**Comment by Tintef** [comment]
Hey @sashberd, for that, I would recommend you to don't rely on the `apiKey` prop to inject the script for you, and just add it yourself on your `index.html`.

I don't think is a super common case to deserve it's own prop
