### ISSUE TITLE
Consulta sobre Input

### ISSUE THREAD

**Issue by FedeRoma** [Tintef/react-google-places-autocomplete#81]
Buenas! Tengo una consulta, en la propiedad renderInput el componente claramente espera un objeto del tipo <input>.
¿Se podría mejorar para que espere algun otro objeto o por ejemplo un TextField de material?

Gracias!

**Comment by Tintef** [comment]
Buenas @FedeRoma 

Se puede utilizar perfectamente un `TextField` de material en la función `renderInput`, te dejo un ejemplo: https://codesandbox.io/s/busy-blackwell-nnreg (vas a tener que poner tu propia `api_key` de google places).

Saludos!

**Comment by Tintef** [comment]
I'll close this one as it's doable with the library as is.

**Comment by FedeRoma** [comment]
Gracias! Un abrazo!
