### ISSUE TITLE
Add X button to clear input

### ISSUE THREAD

**Issue by Tintef** [Tintef/react-google-places-autocomplete#82]
I think a good addition to the library would be a "X" button to clear the field, and that one should trigger a provided callback (if provided).

**Comment by azizcoban** [comment]
Yes we should somehow change the value of the input. Please I need that functionality for my company's project. Otherwise I will remove this component...

**Comment by Tintef** [comment]
@azizcoban This issue is to clear the input value, not change it.

If you want to somehow change the value for something else, you may be able to do something [like this](https://github.com/Tintef/react-google-places-autocomplete/issues/67).

If that doesn't fit your needs, open a new issue with as many details as possible.

Thanks!
