### ISSUE TITLE
Best way to hide the API key within index.html?

### ISSUE THREAD

**Issue by karlkristopher** [Tintef/react-google-places-autocomplete#83]
Does anyone have a suggestion on how too keep your api key secure upon deployment?

I am using an .env file in development, but when I npm run build, the html file reverts to showing the api key. And then if I manually change it back, the deployed version is not accepting the syntax of (%REACT_APP_KEY%).

**Comment by Tintef** [comment]
Hi @karlkristopher, what you are trying to do is not possible. The react compiled code (or any framework) will include any environment variable you use, and this is fine and what you should expect from any JS code.

What you should do is add your domain on the whitelist inside google's console so only the given domain(s) can use your api key.
