### ISSUE TITLE
autoCompletionRequest types not working as expected

### ISSUE THREAD

**Issue by vpugh** [Tintef/react-google-places-autocomplete#85]
When trying to search using a zipcode, I'm not getting any results when I'm using the autoCompletionRequest.
Example:
```
autocompletionRequest={{
  componentRestrictions: {
      country: ['US'],
    },
  types: ['postal_code'],
}}
```

Is this being used properly or can you not use the types like this? I can't use `types: ['(region)']`, it's too restrictive so I was hoping to use an array of a bunch of items. Something like `['postal_code', 'locality', 'administrative_area_level_1', 'neighborhood']` but I can't get a single option to work.

**Comment by Tintef** [comment]
@vpugh I think you can't use types like that on an autocompletion request, you can only use the `(region)` one 😞 

In the weekend I'll play around and have a real answer

**Comment by Tintef** [comment]
@vpugh I'll close this as I confirmed that's not doable with google places autocomplete API.
If someone knows how to do it, please comment below!
