### ISSUE TITLE
Add onInputValueChange function

### ISSUE THREAD

**Issue by chtay1** [Tintef/react-google-places-autocomplete#86]
Would it be possible for you to add an onInputValueChange that is called in the internal changeValue function so that the current input value is available easily outside of the component or would you accept a pull request if it were submitted.

    changeValue = (value) => {
        this.setState({ value });

        if (value.length > 0) {
          this.fetchSuggestions(value);
        } else {
          this.setState({ suggestions: [] });
        }

        if (onInputValueChange)
            onInputValueChange(value);
      }

**Comment by Tintef** [comment]
Hi @chtay1, you can do that already! Please refer to this issue: https://github.com/Tintef/react-google-places-autocomplete/issues/67

**Comment by chtay1** [comment]
Great, thanks! Didn't think of that.
