### ISSUE TITLE
Help with debugging

### ISSUE THREAD

**Issue by Hunartimon** [Tintef/react-google-places-autocomplete#94]
Hi, I'm trying a quite basic setup:

```
import React from 'react';
import GooglePlacesAutocomplete from 'react-google-places-autocomplete';
import 'react-google-places-autocomplete/dist/index.min.css';

const Component = () => (
  <div>
    <GooglePlacesAutocomplete
      apiKey="MY_API_KEY"
      onSelect={console.log}
    />
  </div>
);

export default Component;
```

The api key is fresh and unrestricted, places API is enabled.
Yet after typing in the input, a dropdown list comes up with a 'Loading...' item, and noting more happens.

Any suggestion on what could go wrong here, or how can I debug & check the response from the Places API?

**Comment by Tintef** [comment]
Hey @Hunartimon, a couple things:

1. Check the google script is injected as expected on your page
2. Does the console show any errors?
3. You can check if the script is loaded by typing `window.google.maps.places` on the devtools console, if that doesn't exists, it means that google maps script didn't loaded as expected

**Comment by Hunartimon** [comment]
Thank you for the help!

The issue was not with this library, but I'll describe my solution for future reference.

Although it is stated on google docs (https://developers.google.com/maps/gmp-get-started#enable-api-sdk), that enabling Places API automatically enables other APIs (like Maps JavaScript API), that was not true for me, and Maps JavaScript API had to be enabled too for this to work.

**Comment by Tintef** [comment]
Glad to hear you were able to fix the issue 😄
