### ISSUE TITLE
change react to peer dependency

### ISSUE THREAD

**Issue by macrozone** [Tintef/react-google-places-autocomplete#99]
react should not be a dependency, but a peerDependency.

You should add it as devDependency as well for development

**Comment by Tintef** [comment]
@macrozone Thanks, I'm currently doing a rewrite of the library using TS and I'll be fixing this issue on that 😄

**Comment by Tintef** [comment]
@macrozone  FYI, this is already released as an alpha version, you can install it with:

```yarn add react-google-places-autocomplete@3.0.0-alpha.0```

And you can find the new docs [here](https://tintef.github.io/react-google-places-autocomplete/)

**Comment by Tintef** [comment]
@macrozone This is already merged in master (but still an alpha release)
